using Blackbird.Applications.Sdk.Common.Dictionaries;

namespace Apps.Trello.DataSourceHandlers.Static
{
    public class EmojiDataHandler : IStaticDataSourceHandler
    {
        public Dictionary<string, string> GetData()
        {
            var data = new Dictionary<string, string>
            {
            { "Grinning", "😀 GRINNING FACE" },
            { "Grin", "😁 GRINNING FACE WITH SMILING EYES" },
            { "Joy", "😂 FACE WITH TEARS OF JOY" },
            { "RollingOnTheFloorLaughing", "🤣 ROLLING ON THE FLOOR LAUGHING" },
            { "Smiley", "😃 SMILING FACE WITH OPEN MOUTH" },
            { "Smile", "😄 SMILING FACE WITH OPEN MOUTH AND SMILING EYES" },
            { "SweatSmile", "😅 SMILING FACE WITH OPEN MOUTH AND COLD SWEAT" },
            { "Laughing", "😆 SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES" },
            { "Wink", "😉 WINKING FACE" },
            { "Blush", "😊 SMILING FACE WITH SMILING EYES" },
            { "Yum", "😋 FACE SAVOURING DELICIOUS FOOD" },
            { "Sunglasses", "😎 SMILING FACE WITH SUNGLASSES" },
            { "HeartEyes", "😍 SMILING FACE WITH HEART-SHAPED EYES" },
            { "KissingHeart", "😘 FACE THROWING A KISS" },
            { "Kissing", "😗 KISSING FACE" },
            { "KissingSmilingEyes", "😙 KISSING FACE WITH SMILING EYES" },
            { "KissingClosedEyes", "😚 KISSING FACE WITH CLOSED EYES" },
            { "Relaxed", "☺️ WHITE SMILING FACE" },
            { "SlightlySmilingFace", "🙂 SLIGHTLY SMILING FACE" },
            { "HuggingFace", "🤗 HUGGING FACE" },
            { "StarStruck", "🤩 GRINNING FACE WITH STAR EYES" },
            { "ThinkingFace", "🤔 THINKING FACE" },
            { "FaceWithRaisedEyebrow", "🤨 FACE WITH ONE EYEBROW RAISED" },
            { "NeutralFace", "😐 NEUTRAL FACE" },
            { "Expressionless", "😑 EXPRESSIONLESS FACE" },
            { "NoMouth", "😶 FACE WITHOUT MOUTH" },
            { "FaceWithRollingEyes", "🙄 FACE WITH ROLLING EYES" },
            { "Smirk", "😏 SMIRKING FACE" },
            { "Persevere", "😣 PERSEVERING FACE" },
            { "DisappointedRelieved", "😥 DISAPPOINTED BUT RELIEVED FACE" },
            { "OpenMouth", "😮 FACE WITH OPEN MOUTH" },
            { "ZipperMouthFace", "🤐 ZIPPER-MOUTH FACE" },
            { "Hushed", "😯 HUSHED FACE" },
            { "Sleepy", "😪 SLEEPY FACE" },
            { "TiredFace", "😫 TIRED FACE" },
            { "Sleeping", "😴 SLEEPING FACE" },
            { "Relieved", "😌 RELIEVED FACE" },
            { "StuckOutTongue", "😛 FACE WITH STUCK-OUT TONGUE" },
            { "StuckOutTongueWinkingEye", "😜 FACE WITH STUCK-OUT TONGUE AND WINKING EYE" },
            { "StuckOutTongueClosedEyes", "😝 FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES" },
            { "DroolingFace", "🤤 DROOLING FACE" },
            { "Unamused", "😒 UNAMUSED FACE" },
            { "Sweat", "😓 FACE WITH COLD SWEAT" },
            { "Pensive", "😔 PENSIVE FACE" },
            { "Confused", "😕 CONFUSED FACE" },
            { "UpsideDownFace", "🙃 UPSIDE-DOWN FACE" },
            { "MoneyMouthFace", "🤑 MONEY-MOUTH FACE" },
            { "Astonished", "😲 ASTONISHED FACE" },
            { "SlightlyFrowningFace", "🙁 SLIGHTLY FROWNING FACE" },
            { "Confounded", "😖 CONFOUNDED FACE" },
            { "Disappointed", "😞 DISAPPOINTED FACE" },
            { "Worried", "😟 WORRIED FACE" },
            { "Triumph", "😤 FACE WITH LOOK OF TRIUMPH" },
            { "Cry", "😢 CRYING FACE" },
            { "Sob", "😭 LOUDLY CRYING FACE" },
            { "Frowning", "😦 FROWNING FACE WITH OPEN MOUTH" },
            { "Anguished", "😧 ANGUISHED FACE" },
            { "Fearful", "😨 FEARFUL FACE" },
            { "Weary", "😩 WEARY FACE" },
            { "ExplodingHead", "🤯 SHOCKED FACE WITH EXPLODING HEAD" },
            { "Grimacing", "😬 GRIMACING FACE" },
            { "ColdSweat", "😰 FACE WITH OPEN MOUTH AND COLD SWEAT" },
            { "Scream", "😱 FACE SCREAMING IN FEAR" },
            { "Flushed", "😳 FLUSHED FACE" },
            { "ZanyFace", "🤪 GRINNING FACE WITH ONE LARGE AND ONE SMALL EYE" },
            { "DizzyFace", "😵 DIZZY FACE" },
            { "Rage", "😡 POUTING FACE" },
            { "Angry", "😠 ANGRY FACE" },
            { "FaceWithSymbolsOnMouth", "🤬 SERIOUS FACE WITH SYMBOLS COVERING MOUTH" },
            { "Mask", "😷 FACE WITH MEDICAL MASK" },
            { "FaceWithThermometer", "🤒 FACE WITH THERMOMETER" },
            { "FaceWithHeadBandage", "🤕 FACE WITH HEAD-BANDAGE" },
            { "NauseatedFace", "🤢 NAUSEATED FACE" },
            { "FaceVomiting", "🤮 FACE WITH OPEN MOUTH VOMITING" },
            { "SneezingFace", "🤧 SNEEZING FACE" },
            { "Innocent", "😇 SMILING FACE WITH HALO" },
            { "FaceWithCowboyHat", "🤠 FACE WITH COWBOY HAT" },
            { "LyingFace", "🤥 LYING FACE" },
            { "ShushingFace", "🤫 FACE WITH FINGER COVERING CLOSED LIPS" },
            { "FaceWithHandOverMouth", "🤭 SMILING FACE WITH SMILING EYES AND HAND COVERING MOUTH" },
            { "FaceWithMonocle", "🧐 FACE WITH MONOCLE" },
            { "NerdFace", "🤓 NERD FACE" },
            { "SmilingImp", "😈 SMILING FACE WITH HORNS" },
            { "Imp", "👿 IMP" },
            { "ClownFace", "🤡 CLOWN FACE" },
            { "JapaneseOgre", "👹 JAPANESE OGRE" },
            { "JapaneseGoblin", "👺 JAPANESE GOBLIN" },
            { "Skull", "💀 SKULL" },
            { "Ghost", "👻 GHOST" },
            { "Alien", "👽 EXTRATERRESTRIAL ALIEN" },
            { "SpaceInvader", "👾 ALIEN MONSTER" },
            { "RobotFace", "🤖 ROBOT FACE" },
            { "Hankey", "💩 PILE OF POO" },
            { "SmileyCat", "😺 SMILING CAT FACE WITH OPEN MOUTH" },
            { "SmileCat", "😸 GRINNING CAT FACE WITH SMILING EYES" },
            { "JoyCat", "😹 CAT FACE WITH TEARS OF JOY" },
            { "HeartEyesCat", "😻 SMILING CAT FACE WITH HEART-SHAPED EYES" },
            { "SmirkCat", "😼 CAT FACE WITH WRY SMILE" },
            { "KissingCat", "😽 KISSING CAT FACE WITH CLOSED EYES" },
            { "ScreamCat", "🙀 WEARY CAT FACE" },
            { "CryingCatFace", "😿 CRYING CAT FACE" },
            { "PoutingCat", "😾 POUTING CAT FACE" },
            { "SeeNoEvil", "🙈 SEE-NO-EVIL MONKEY" },
            { "HearNoEvil", "🙉 HEAR-NO-EVIL MONKEY" },
            { "SpeakNoEvil", "🙊 SPEAK-NO-EVIL MONKEY" },
            { "Baby", "👶 BABY" },
            { "Baby_Light", "👶🏻 BABY" },
            { "Baby_MediumLight", "👶🏼 BABY" },
            { "Baby_Medium", "👶🏽 BABY" },
            { "Baby_MediumDark", "👶🏾 BABY" },
            { "Baby_Dark", "👶🏿 BABY" },
            { "Child", "🧒 CHILD" },
            { "Child_Light", "🧒🏻 CHILD" },
            { "Child_MediumLight", "🧒🏼 CHILD" },
            { "Child_Medium", "🧒🏽 CHILD" },
            { "Child_MediumDark", "🧒🏾 CHILD" },
            { "Child_Dark", "🧒🏿 CHILD" },
            { "Boy", "👦 BOY" },
            { "Boy_Light", "👦🏻 BOY" },
            { "Boy_MediumLight", "👦🏼 BOY" },
            { "Boy_Medium", "👦🏽 BOY" },
            { "Boy_MediumDark", "👦🏾 BOY" },
            { "Boy_Dark", "👦🏿 BOY" },
            { "Girl", "👧 GIRL" },
            { "Girl_Light", "👧🏻 GIRL" },
            { "Girl_MediumLight", "👧🏼 GIRL" },
            { "Girl_Medium", "👧🏽 GIRL" },
            { "Girl_MediumDark", "👧🏾 GIRL" },
            { "Girl_Dark", "👧🏿 GIRL" },
            { "Adult", "🧑 ADULT" },
            { "Adult_Light", "🧑🏻 ADULT" },
            { "Adult_MediumLight", "🧑🏼 ADULT" },
            { "Adult_Medium", "🧑🏽 ADULT" },
            { "Adult_MediumDark", "🧑🏾 ADULT" },
            { "Adult_Dark", "🧑🏿 ADULT" },
            { "Man", "👨 MAN" },
            { "Man_Light", "👨🏻 MAN" },
            { "Man_MediumLight", "👨🏼 MAN" },
            { "Man_Medium", "👨🏽 MAN" },
            { "Man_MediumDark", "👨🏾 MAN" },
            { "Man_Dark", "👨🏿 MAN" },
            { "BeardedPerson", "🧔 BEARDED PERSON" },
            { "BeardedPerson_Light", "🧔🏻 BEARDED PERSON" },
            { "BeardedPerson_MediumLight", "🧔🏼 BEARDED PERSON" },
            { "BeardedPerson_Medium", "🧔🏽 BEARDED PERSON" },
            { "BeardedPerson_MediumDark", "🧔🏾 BEARDED PERSON" },
            { "BeardedPerson_Dark", "🧔🏿 BEARDED PERSON" },
            { "Woman", "👩 WOMAN" },
            { "Woman_Light", "👩🏻 WOMAN" },
            { "Woman_MediumLight", "👩🏼 WOMAN" },
            { "Woman_Medium", "👩🏽 WOMAN" },
            { "Woman_MediumDark", "👩🏾 WOMAN" },
            { "Woman_Dark", "👩🏿 WOMAN" },
            { "OlderAdult", "🧓 OLDER ADULT" },
            { "OlderAdult_Light", "🧓🏻 OLDER ADULT" },
            { "OlderAdult_MediumLight", "🧓🏼 OLDER ADULT" },
            { "OlderAdult_Medium", "🧓🏽 OLDER ADULT" },
            { "OlderAdult_MediumDark", "🧓🏾 OLDER ADULT" },
            { "OlderAdult_Dark", "🧓🏿 OLDER ADULT" },
            { "OlderMan", "👴 OLDER MAN" },
            { "OlderMan_Light", "👴🏻 OLDER MAN" },
            { "OlderMan_MediumLight", "👴🏼 OLDER MAN" },
            { "OlderMan_Medium", "👴🏽 OLDER MAN" },
            { "OlderMan_MediumDark", "👴🏾 OLDER MAN" },
            { "OlderMan_Dark", "👴🏿 OLDER MAN" },
            { "OlderWoman", "👵 OLDER WOMAN" },
            { "OlderWoman_Light", "👵🏻 OLDER WOMAN" },
            { "OlderWoman_MediumLight", "👵🏼 OLDER WOMAN" },
            { "OlderWoman_Medium", "👵🏽 OLDER WOMAN" },
            { "OlderWoman_MediumDark", "👵🏾 OLDER WOMAN" },
            { "OlderWoman_Dark", "👵🏿 OLDER WOMAN" },
            { "Prince", "🤴 PRINCE" },
            { "Prince_Light", "🤴🏻 PRINCE" },
            { "Prince_MediumLight", "🤴🏼 PRINCE" },
            { "Prince_Medium", "🤴🏽 PRINCE" },
            { "Prince_MediumDark", "🤴🏾 PRINCE" },
            { "Prince_Dark", "🤴🏿 PRINCE" },
            { "Princess", "👸 PRINCESS" },
            { "Princess_Light", "👸🏻 PRINCESS" },
            { "Princess_MediumLight", "👸🏼 PRINCESS" },
            { "Princess_Medium", "👸🏽 PRINCESS" },
            { "Princess_MediumDark", "👸🏾 PRINCESS" },
            { "Princess_Dark", "👸🏿 PRINCESS" },
            { "ManWithGuaPiMao", "👲 MAN WITH GUA PI MAO" },
            { "ManWithGuaPiMao_Light", "👲🏻 MAN WITH GUA PI MAO" },
            { "ManWithGuaPiMao_MediumLight", "👲🏼 MAN WITH GUA PI MAO" },
            { "ManWithGuaPiMao_Medium", "👲🏽 MAN WITH GUA PI MAO" },
            { "ManWithGuaPiMao_MediumDark", "👲🏾 MAN WITH GUA PI MAO" },
            { "ManWithGuaPiMao_Dark", "👲🏿 MAN WITH GUA PI MAO" },
            { "PersonWithHeadscarf", "🧕 PERSON WITH HEADSCARF" },
            { "PersonWithHeadscarf_Light", "🧕🏻 PERSON WITH HEADSCARF" },
            { "PersonWithHeadscarf_MediumLight", "🧕🏼 PERSON WITH HEADSCARF" },
            { "PersonWithHeadscarf_Medium", "🧕🏽 PERSON WITH HEADSCARF" },
            { "PersonWithHeadscarf_MediumDark", "🧕🏾 PERSON WITH HEADSCARF" },
            { "PersonWithHeadscarf_Dark", "🧕🏿 PERSON WITH HEADSCARF" },
            { "ManInTuxedo", "🤵 MAN IN TUXEDO" },
            { "ManInTuxedo_Light", "🤵🏻 MAN IN TUXEDO" },
            { "ManInTuxedo_MediumLight", "🤵🏼 MAN IN TUXEDO" },
            { "ManInTuxedo_Medium", "🤵🏽 MAN IN TUXEDO" },
            { "ManInTuxedo_MediumDark", "🤵🏾 MAN IN TUXEDO" },
            { "ManInTuxedo_Dark", "🤵🏿 MAN IN TUXEDO" },
            { "BrideWithVeil", "👰 BRIDE WITH VEIL" },
            { "BrideWithVeil_Light", "👰🏻 BRIDE WITH VEIL" },
            { "BrideWithVeil_MediumLight", "👰🏼 BRIDE WITH VEIL" },
            { "BrideWithVeil_Medium", "👰🏽 BRIDE WITH VEIL" },
            { "BrideWithVeil_MediumDark", "👰🏾 BRIDE WITH VEIL" },
            { "BrideWithVeil_Dark", "👰🏿 BRIDE WITH VEIL" },
            { "PregnantWoman", "🤰 PREGNANT WOMAN" },
            { "PregnantWoman_Light", "🤰🏻 PREGNANT WOMAN" },
            { "PregnantWoman_MediumLight", "🤰🏼 PREGNANT WOMAN" },
            { "PregnantWoman_Medium", "🤰🏽 PREGNANT WOMAN" },
            { "PregnantWoman_MediumDark", "🤰🏾 PREGNANT WOMAN" },
            { "PregnantWoman_Dark", "🤰🏿 PREGNANT WOMAN" },
            { "BreastFeeding", "🤱 BREAST-FEEDING" },
            { "BreastFeeding_Light", "🤱🏻 BREAST-FEEDING" },
            { "BreastFeeding_MediumLight", "🤱🏼 BREAST-FEEDING" },
            { "BreastFeeding_Medium", "🤱🏽 BREAST-FEEDING" },
            { "BreastFeeding_MediumDark", "🤱🏾 BREAST-FEEDING" },
            { "BreastFeeding_Dark", "🤱🏿 BREAST-FEEDING" },
            { "Angel", "👼 BABY ANGEL" },
            { "Angel_Light", "👼🏻 BABY ANGEL" },
            { "Angel_MediumLight", "👼🏼 BABY ANGEL" },
            { "Angel_Medium", "👼🏽 BABY ANGEL" },
            { "Angel_MediumDark", "👼🏾 BABY ANGEL" },
            { "Angel_Dark", "👼🏿 BABY ANGEL" },
            { "Santa", "🎅 FATHER CHRISTMAS" },
            { "Santa_Light", "🎅🏻 FATHER CHRISTMAS" },
            { "Santa_MediumLight", "🎅🏼 FATHER CHRISTMAS" },
            { "Santa_Medium", "🎅🏽 FATHER CHRISTMAS" },
            { "Santa_MediumDark", "🎅🏾 FATHER CHRISTMAS" },
            { "Santa_Dark", "🎅🏿 FATHER CHRISTMAS" },
            { "MrsClaus", "🤶 MOTHER CHRISTMAS" },
            { "MrsClaus_Light", "🤶🏻 MOTHER CHRISTMAS" },
            { "MrsClaus_MediumLight", "🤶🏼 MOTHER CHRISTMAS" },
            { "MrsClaus_Medium", "🤶🏽 MOTHER CHRISTMAS" },
            { "MrsClaus_MediumDark", "🤶🏾 MOTHER CHRISTMAS" },
            { "MrsClaus_Dark", "🤶🏿 MOTHER CHRISTMAS" },
            { "Dancer", "💃 DANCER" },
            { "Dancer_Light", "💃🏻 DANCER" },
            { "Dancer_MediumLight", "💃🏼 DANCER" },
            { "Dancer_Medium", "💃🏽 DANCER" },
            { "Dancer_MediumDark", "💃🏾 DANCER" },
            { "Dancer_Dark", "💃🏿 DANCER" },
            { "ManDancing", "🕺 MAN DANCING" },
            { "ManDancing_Light", "🕺🏻 MAN DANCING" },
            { "ManDancing_MediumLight", "🕺🏼 MAN DANCING" },
            { "ManDancing_Medium", "🕺🏽 MAN DANCING" },
            { "ManDancing_MediumDark", "🕺🏾 MAN DANCING" },
            { "ManDancing_Dark", "🕺🏿 MAN DANCING" },
            { "Bath", "🛀 BATH" },
            { "Bath_Light", "🛀🏻 BATH" },
            { "Bath_MediumLight", "🛀🏼 BATH" },
            { "Bath_Medium", "🛀🏽 BATH" },
            { "Bath_MediumDark", "🛀🏾 BATH" },
            { "Bath_Dark", "🛀🏿 BATH" },
            { "SleepingAccommodation", "🛌 SLEEPING ACCOMMODATION" },
            { "SleepingAccommodation_Light", "🛌🏻 SLEEPING ACCOMMODATION" },
            { "SleepingAccommodation_MediumLight", "🛌🏼 SLEEPING ACCOMMODATION" },
            { "SleepingAccommodation_Medium", "🛌🏽 SLEEPING ACCOMMODATION" },
            { "SleepingAccommodation_MediumDark", "🛌🏾 SLEEPING ACCOMMODATION" },
            { "SleepingAccommodation_Dark", "🛌🏿 SLEEPING ACCOMMODATION" },
            { "BustInSilhouette", "👤 BUST IN SILHOUETTE" },
            { "BustsInSilhouette", "👥 BUSTS IN SILHOUETTE" },
            { "Fencer", "🤺 FENCER" },
            { "HorseRacing", "🏇 HORSE RACING" },
            { "HorseRacing_Light", "🏇🏻 HORSE RACING" },
            { "HorseRacing_MediumLight", "🏇🏼 HORSE RACING" },
            { "HorseRacing_Medium", "🏇🏽 HORSE RACING" },
            { "HorseRacing_MediumDark", "🏇🏾 HORSE RACING" },
            { "HorseRacing_Dark", "🏇🏿 HORSE RACING" },
            { "Snowboarder", "🏂 SNOWBOARDER" },
            { "Snowboarder_Light", "🏂🏻 SNOWBOARDER" },
            { "Snowboarder_MediumLight", "🏂🏼 SNOWBOARDER" },
            { "Snowboarder_Medium", "🏂🏽 SNOWBOARDER" },
            { "Snowboarder_MediumDark", "🏂🏾 SNOWBOARDER" },
            { "Snowboarder_Dark", "🏂🏿 SNOWBOARDER" },
            { "Couple", "👫 MAN AND WOMAN HOLDING HANDS" },
            { "TwoMenHoldingHands", "👬 TWO MEN HOLDING HANDS" },
            { "TwoWomenHoldingHands", "👭 TWO WOMEN HOLDING HANDS" },
            { "Couplekiss", "💏 KISS" },
            { "CoupleWithHeart", "💑 COUPLE WITH HEART" },
            { "Family", "👪 FAMILY" },
            { "Selfie", "🤳 SELFIE" },
            { "Selfie_Light", "🤳🏻 SELFIE" },
            { "Selfie_MediumLight", "🤳🏼 SELFIE" },
            { "Selfie_Medium", "🤳🏽 SELFIE" },
            { "Selfie_MediumDark", "🤳🏾 SELFIE" },
            { "Selfie_Dark", "🤳🏿 SELFIE" },
            { "Muscle", "💪 FLEXED BICEPS" },
            { "Muscle_Light", "💪🏻 FLEXED BICEPS" },
            { "Muscle_MediumLight", "💪🏼 FLEXED BICEPS" },
            { "Muscle_Medium", "💪🏽 FLEXED BICEPS" },
            { "Muscle_MediumDark", "💪🏾 FLEXED BICEPS" },
            { "Muscle_Dark", "💪🏿 FLEXED BICEPS" },
            { "PointLeft", "👈 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointLeft_Light", "👈🏻 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointLeft_MediumLight", "👈🏼 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointLeft_Medium", "👈🏽 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointLeft_MediumDark", "👈🏾 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointLeft_Dark", "👈🏿 WHITE LEFT POINTING BACKHAND INDEX" },
            { "PointRight", "👉 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointRight_Light", "👉🏻 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointRight_MediumLight", "👉🏼 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointRight_Medium", "👉🏽 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointRight_MediumDark", "👉🏾 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointRight_Dark", "👉🏿 WHITE RIGHT POINTING BACKHAND INDEX" },
            { "PointUp", "☝️ WHITE UP POINTING INDEX" },
            { "PointUp_Light", "☝🏻 WHITE UP POINTING INDEX" },
            { "PointUp_MediumLight", "☝🏼 WHITE UP POINTING INDEX" },
            { "PointUp_Medium", "☝🏽 WHITE UP POINTING INDEX" },
            { "PointUp_MediumDark", "☝🏾 WHITE UP POINTING INDEX" },
            { "PointUp_Dark", "☝🏿 WHITE UP POINTING INDEX" },
            { "PointUp2", "👆 WHITE UP POINTING BACKHAND INDEX" },
            { "PointUp2_Light", "👆🏻 WHITE UP POINTING BACKHAND INDEX" },
            { "PointUp2_MediumLight", "👆🏼 WHITE UP POINTING BACKHAND INDEX" },
            { "PointUp2_Medium", "👆🏽 WHITE UP POINTING BACKHAND INDEX" },
            { "PointUp2_MediumDark", "👆🏾 WHITE UP POINTING BACKHAND INDEX" },
            { "PointUp2_Dark", "👆🏿 WHITE UP POINTING BACKHAND INDEX" },
            { "MiddleFinger", "🖕 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "MiddleFinger_Light", "🖕🏻 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "MiddleFinger_MediumLight", "🖕🏼 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "MiddleFinger_Medium", "🖕🏽 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "MiddleFinger_MediumDark", "🖕🏾 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "MiddleFinger_Dark", "🖕🏿 REVERSED HAND WITH MIDDLE FINGER EXTENDED" },
            { "PointDown", "👇 WHITE DOWN POINTING BACKHAND INDEX" },
            { "PointDown_Light", "👇🏻 WHITE DOWN POINTING BACKHAND INDEX" },
            { "PointDown_MediumLight", "👇🏼 WHITE DOWN POINTING BACKHAND INDEX" },
            { "PointDown_Medium", "👇🏽 WHITE DOWN POINTING BACKHAND INDEX" },
            { "PointDown_MediumDark", "👇🏾 WHITE DOWN POINTING BACKHAND INDEX" },
            { "PointDown_Dark", "👇🏿 WHITE DOWN POINTING BACKHAND INDEX" },
            { "V", "✌️ VICTORY HAND" },
            { "V_Light", "✌🏻 VICTORY HAND" },
            { "V_MediumLight", "✌🏼 VICTORY HAND" },
            { "V_Medium", "✌🏽 VICTORY HAND" },
            { "V_MediumDark", "✌🏾 VICTORY HAND" },
            { "V_Dark", "✌🏿 VICTORY HAND" },
            { "CrossedFingers", "🤞 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "CrossedFingers_Light", "🤞🏻 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "CrossedFingers_MediumLight", "🤞🏼 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "CrossedFingers_Medium", "🤞🏽 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "CrossedFingers_MediumDark", "🤞🏾 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "CrossedFingers_Dark", "🤞🏿 HAND WITH INDEX AND MIDDLE FINGERS CROSSED" },
            { "SpockHand", "🖖 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "SpockHand_Light", "🖖🏻 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "SpockHand_MediumLight", "🖖🏼 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "SpockHand_Medium", "🖖🏽 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "SpockHand_MediumDark", "🖖🏾 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "SpockHand_Dark", "🖖🏿 RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS" },
            { "TheHorns", "🤘 SIGN OF THE HORNS" },
            { "TheHorns_Light", "🤘🏻 SIGN OF THE HORNS" },
            { "TheHorns_MediumLight", "🤘🏼 SIGN OF THE HORNS" },
            { "TheHorns_Medium", "🤘🏽 SIGN OF THE HORNS" },
            { "TheHorns_MediumDark", "🤘🏾 SIGN OF THE HORNS" },
            { "TheHorns_Dark", "🤘🏿 SIGN OF THE HORNS" },
            { "CallMeHand", "🤙 CALL ME HAND" },
            { "CallMeHand_Light", "🤙🏻 CALL ME HAND" },
            { "CallMeHand_MediumLight", "🤙🏼 CALL ME HAND" },
            { "CallMeHand_Medium", "🤙🏽 CALL ME HAND" },
            { "CallMeHand_MediumDark", "🤙🏾 CALL ME HAND" },
            { "CallMeHand_Dark", "🤙🏿 CALL ME HAND" },
            { "Hand", "✋ RAISED HAND" },
            { "Hand_Light", "✋🏻 RAISED HAND" },
            { "Hand_MediumLight", "✋🏼 RAISED HAND" },
            { "Hand_Medium", "✋🏽 RAISED HAND" },
            { "Hand_MediumDark", "✋🏾 RAISED HAND" },
            { "Hand_Dark", "✋🏿 RAISED HAND" },
            { "OkHand", "👌 OK HAND SIGN" },
            { "OkHand_Light", "👌🏻 OK HAND SIGN" },
            { "OkHand_MediumLight", "👌🏼 OK HAND SIGN" },
            { "OkHand_Medium", "👌🏽 OK HAND SIGN" },
            { "OkHand_MediumDark", "👌🏾 OK HAND SIGN" },
            { "OkHand_Dark", "👌🏿 OK HAND SIGN" },
            { "ThumbsUp", "👍 THUMBS UP SIGN" },
            { "ThumbsUp_Light", "👍🏻 THUMBS UP SIGN" },
            { "ThumbsUp_MediumLight", "👍🏼 THUMBS UP SIGN" },
            { "ThumbsUp_Medium", "👍🏽 THUMBS UP SIGN" },
            { "ThumbsUp_MediumDark", "👍🏾 THUMBS UP SIGN" },
            { "ThumbsUp_Dark", "👍🏿 THUMBS UP SIGN" },
            { "ThumbsDown", "👎 THUMBS DOWN SIGN" },
            { "ThumbsDown_Light", "👎🏻 THUMBS DOWN SIGN" },
            { "ThumbsDown_MediumLight", "👎🏼 THUMBS DOWN SIGN" },
            { "ThumbsDown_Medium", "👎🏽 THUMBS DOWN SIGN" },
            { "ThumbsDown_MediumDark", "👎🏾 THUMBS DOWN SIGN" },
            { "ThumbsDown_Dark", "👎🏿 THUMBS DOWN SIGN" },
            { "Fist", "✊ RAISED FIST" },
            { "Fist_Light", "✊🏻 RAISED FIST" },
            { "Fist_MediumLight", "✊🏼 RAISED FIST" },
            { "Fist_Medium", "✊🏽 RAISED FIST" },
            { "Fist_MediumDark", "✊🏾 RAISED FIST" },
            { "Fist_Dark", "✊🏿 RAISED FIST" },
            { "Facepunch", "👊 FISTED HAND SIGN" },
            { "Facepunch_Light", "👊🏻 FISTED HAND SIGN" },
            { "Facepunch_MediumLight", "👊🏼 FISTED HAND SIGN" },
            { "Facepunch_Medium", "👊🏽 FISTED HAND SIGN" },
            { "Facepunch_MediumDark", "👊🏾 FISTED HAND SIGN" },
            { "Facepunch_Dark", "👊🏿 FISTED HAND SIGN" },
            { "LeftFacingFist", "🤛 LEFT-FACING FIST" },
            { "LeftFacingFist_Light", "🤛🏻 LEFT-FACING FIST" },
            { "LeftFacingFist_MediumLight", "🤛🏼 LEFT-FACING FIST" },
            { "LeftFacingFist_Medium", "🤛🏽 LEFT-FACING FIST" },
            { "LeftFacingFist_MediumDark", "🤛🏾 LEFT-FACING FIST" },
            { "LeftFacingFist_Dark", "🤛🏿 LEFT-FACING FIST" },
            { "RightFacingFist", "🤜 RIGHT-FACING FIST" },
            { "RightFacingFist_Light", "🤜🏻 RIGHT-FACING FIST" },
            { "RightFacingFist_MediumLight", "🤜🏼 RIGHT-FACING FIST" },
            { "RightFacingFist_Medium", "🤜🏽 RIGHT-FACING FIST" },
            { "RightFacingFist_MediumDark", "🤜🏾 RIGHT-FACING FIST" },
            { "RightFacingFist_Dark", "🤜🏿 RIGHT-FACING FIST" },
            { "RaisedBackOfHand", "🤚 RAISED BACK OF HAND" },
            { "RaisedBackOfHand_Light", "🤚🏻 RAISED BACK OF HAND" },
            { "RaisedBackOfHand_MediumLight", "🤚🏼 RAISED BACK OF HAND" },
            { "RaisedBackOfHand_Medium", "🤚🏽 RAISED BACK OF HAND" },
            { "RaisedBackOfHand_MediumDark", "🤚🏾 RAISED BACK OF HAND" },
            { "RaisedBackOfHand_Dark", "🤚🏿 RAISED BACK OF HAND" },
            { "Wave", "👋 WAVING HAND SIGN" },
            { "Wave_Light", "👋🏻 WAVING HAND SIGN" },
            { "Wave_MediumLight", "👋🏼 WAVING HAND SIGN" },
            { "Wave_Medium", "👋🏽 WAVING HAND SIGN" },
            { "Wave_MediumDark", "👋🏾 WAVING HAND SIGN" },
            { "Wave_Dark", "👋🏿 WAVING HAND SIGN" },
            { "ILoveYouHandSign", "🤟 I LOVE YOU HAND SIGN" },
            { "ILoveYouHandSign_Light", "🤟🏻 I LOVE YOU HAND SIGN" },
            { "ILoveYouHandSign_MediumLight", "🤟🏼 I LOVE YOU HAND SIGN" },
            { "ILoveYouHandSign_Medium", "🤟🏽 I LOVE YOU HAND SIGN" },
            { "ILoveYouHandSign_MediumDark", "🤟🏾 I LOVE YOU HAND SIGN" },
            { "ILoveYouHandSign_Dark", "🤟🏿 I LOVE YOU HAND SIGN" },
            { "Clap", "👏 CLAPPING HANDS SIGN" },
            { "Clap_Light", "👏🏻 CLAPPING HANDS SIGN" },
            { "Clap_MediumLight", "👏🏼 CLAPPING HANDS SIGN" },
            { "Clap_Medium", "👏🏽 CLAPPING HANDS SIGN" },
            { "Clap_MediumDark", "👏🏾 CLAPPING HANDS SIGN" },
            { "Clap_Dark", "👏🏿 CLAPPING HANDS SIGN" },
            { "OpenHands", "👐 OPEN HANDS SIGN" },
            { "OpenHands_Light", "👐🏻 OPEN HANDS SIGN" },
            { "OpenHands_MediumLight", "👐🏼 OPEN HANDS SIGN" },
            { "OpenHands_Medium", "👐🏽 OPEN HANDS SIGN" },
            { "OpenHands_MediumDark", "👐🏾 OPEN HANDS SIGN" },
            { "OpenHands_Dark", "👐🏿 OPEN HANDS SIGN" },
            { "RaisedHands", "🙌 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "RaisedHands_Light", "🙌🏻 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "RaisedHands_MediumLight", "🙌🏼 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "RaisedHands_Medium", "🙌🏽 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "RaisedHands_MediumDark", "🙌🏾 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "RaisedHands_Dark", "🙌🏿 PERSON RAISING BOTH HANDS IN CELEBRATION" },
            { "PalmsUpTogether", "🤲 PALMS UP TOGETHER" },
            { "PalmsUpTogether_Light", "🤲🏻 PALMS UP TOGETHER" },
            { "PalmsUpTogether_MediumLight", "🤲🏼 PALMS UP TOGETHER" },
            { "PalmsUpTogether_Medium", "🤲🏽 PALMS UP TOGETHER" },
            { "PalmsUpTogether_MediumDark", "🤲🏾 PALMS UP TOGETHER" },
            { "PalmsUpTogether_Dark", "🤲🏿 PALMS UP TOGETHER" },
            { "Pray", "🙏 PERSON WITH FOLDED HANDS" },
            { "Pray_Light", "🙏🏻 PERSON WITH FOLDED HANDS" },
            { "Pray_MediumLight", "🙏🏼 PERSON WITH FOLDED HANDS" },
            { "Pray_Medium", "🙏🏽 PERSON WITH FOLDED HANDS" },
            { "Pray_MediumDark", "🙏🏾 PERSON WITH FOLDED HANDS" },
            { "Pray_Dark", "🙏🏿 PERSON WITH FOLDED HANDS" },
            { "Handshake", "🤝 HANDSHAKE" },
            { "NailCare", "💅 NAIL POLISH" },
            { "NailCare_Light", "💅🏻 NAIL POLISH" },
            { "NailCare_MediumLight", "💅🏼 NAIL POLISH" },
            { "NailCare_Medium", "💅🏽 NAIL POLISH" },
            { "NailCare_MediumDark", "💅🏾 NAIL POLISH" },
            { "NailCare_Dark", "💅🏿 NAIL POLISH" },
            { "Ear", "👂 EAR" },
            { "Ear_Light", "👂🏻 EAR" },
            { "Ear_MediumLight", "👂🏼 EAR" },
            { "Ear_Medium", "👂🏽 EAR" },
            { "Ear_MediumDark", "👂🏾 EAR" },
            { "Ear_Dark", "👂🏿 EAR" },
            { "Nose", "👃 NOSE" },
            { "Nose_Light", "👃🏻 NOSE" },
            { "Nose_MediumLight", "👃🏼 NOSE" },
            { "Nose_Medium", "👃🏽 NOSE" },
            { "Nose_MediumDark", "👃🏾 NOSE" },
            { "Nose_Dark", "👃🏿 NOSE" },
            { "Footprints", "👣 FOOTPRINTS" },
            { "Eyes", "👀 EYES" },
            { "Brain", "🧠 BRAIN" },
            { "Tongue", "👅 TONGUE" },
            { "Lips", "👄 MOUTH" },
            { "SkinTone2", "🏻 EMOJI MODIFIER FITZPATRICK TYPE-1-2" },
            { "SkinTone3", "🏼 EMOJI MODIFIER FITZPATRICK TYPE-3" },
            { "SkinTone4", "🏽 EMOJI MODIFIER FITZPATRICK TYPE-4" },
            { "SkinTone5", "🏾 EMOJI MODIFIER FITZPATRICK TYPE-5" },
            { "SkinTone6", "🏿 EMOJI MODIFIER FITZPATRICK TYPE-6" },
            { "Kiss", "💋 KISS MARK" },
            { "Cupid", "💘 HEART WITH ARROW" },
            { "GiftHeart", "💝 HEART WITH RIBBON" },
            { "SparklingHeart", "💖 SPARKLING HEART" },
            { "Heartpulse", "💗 GROWING HEART" },
            { "Heartbeat", "💓 BEATING HEART" },
            { "RevolvingHearts", "💞 REVOLVING HEARTS" },
            { "TwoHearts", "💕 TWO HEARTS" },
            { "LoveLetter", "💌 LOVE LETTER" },
            { "BrokenHeart", "💔 BROKEN HEART" },
            { "Heart", "❤️ HEAVY BLACK HEART" },
            { "OrangeHeart", "🧡 ORANGE HEART" },
            { "YellowHeart", "💛 YELLOW HEART" },
            { "GreenHeart", "💚 GREEN HEART" },
            { "BlueHeart", "💙 BLUE HEART" },
            { "PurpleHeart", "💜 PURPLE HEART" },
            { "BlackHeart", "🖤 BLACK HEART" },
            { "HeartDecoration", "💟 HEART DECORATION" },
            { "Zzz", "💤 SLEEPING SYMBOL" },
            { "Anger", "💢 ANGER SYMBOL" },
            { "Bomb", "💣 BOMB" },
            { "Boom", "💥 COLLISION SYMBOL" },
            { "SweatDrops", "💦 SPLASHING SWEAT SYMBOL" },
            { "Dash", "💨 DASH SYMBOL" },
            { "Dizzy", "💫 DIZZY SYMBOL" },
            { "SpeechBalloon", "💬 SPEECH BALLOON" },
            { "ThoughtBalloon", "💭 THOUGHT BALLOON" },
            { "Eyeglasses", "👓 EYEGLASSES" },
            { "Necktie", "👔 NECKTIE" },
            { "Shirt", "👕 T-SHIRT" },
            { "Jeans", "👖 JEANS" },
            { "Scarf", "🧣 SCARF" },
            { "Gloves", "🧤 GLOVES" },
            { "Coat", "🧥 COAT" },
            { "Socks", "🧦 SOCKS" },
            { "Dress", "👗 DRESS" },
            { "Kimono", "👘 KIMONO" },
            { "Bikini", "👙 BIKINI" },
            { "WomansClothes", "👚 WOMANS CLOTHES" },
            { "Purse", "👛 PURSE" },
            { "Handbag", "👜 HANDBAG" },
            { "Pouch", "👝 POUCH" },
            { "SchoolSatchel", "🎒 SCHOOL SATCHEL" },
            { "MansShoe", "👞 MANS SHOE" },
            { "AthleticShoe", "👟 ATHLETIC SHOE" },
            { "HighHeel", "👠 HIGH-HEELED SHOE" },
            { "Sandal", "👡 WOMANS SANDAL" },
            { "Boot", "👢 WOMANS BOOTS" },
            { "Crown", "👑 CROWN" },
            { "WomansHat", "👒 WOMANS HAT" },
            { "Tophat", "🎩 TOP HAT" },
            { "MortarBoard", "🎓 GRADUATION CAP" },
            { "BilledCap", "🧢 BILLED CAP" },
            { "PrayerBeads", "📿 PRAYER BEADS" },
            { "Lipstick", "💄 LIPSTICK" },
            { "Ring", "💍 RING" },
            { "Gem", "💎 GEM STONE" },
            { "MonkeyFace", "🐵 MONKEY FACE" },
            { "Monkey", "🐒 MONKEY" },
            { "Gorilla", "🦍 GORILLA" },
            { "Dog", "🐶 DOG FACE" },
            { "Dog2", "🐕 DOG" },
            { "Poodle", "🐩 POODLE" },
            { "Wolf", "🐺 WOLF FACE" },
            { "FoxFace", "🦊 FOX FACE" },
            { "Cat", "🐱 CAT FACE" },
            { "Cat2", "🐈 CAT" },
            { "LionFace", "🦁 LION FACE" },
            { "Tiger", "🐯 TIGER FACE" },
            { "Tiger2", "🐅 TIGER" },
            { "Leopard", "🐆 LEOPARD" },
            { "Horse", "🐴 HORSE FACE" },
            { "Racehorse", "🐎 HORSE" },
            { "UnicornFace", "🦄 UNICORN FACE" },
            { "ZebraFace", "🦓 ZEBRA FACE" },
            { "Deer", "🦌 DEER" },
            { "Cow", "🐮 COW FACE" },
            { "Ox", "🐂 OX" },
            { "WaterBuffalo", "🐃 WATER BUFFALO" },
            { "Cow2", "🐄 COW" },
            { "Pig", "🐷 PIG FACE" },
            { "Pig2", "🐖 PIG" },
            { "Boar", "🐗 BOAR" },
            { "PigNose", "🐽 PIG NOSE" },
            { "Ram", "🐏 RAM" },
            { "Sheep", "🐑 SHEEP" },
            { "Goat", "🐐 GOAT" },
            { "DromedaryCamel", "🐪 DROMEDARY CAMEL" },
            { "Camel", "🐫 BACTRIAN CAMEL" },
            { "GiraffeFace", "🦒 GIRAFFE FACE" },
            { "Elephant", "🐘 ELEPHANT" },
            { "Rhinoceros", "🦏 RHINOCEROS" },
            { "Mouse", "🐭 MOUSE FACE" },
            { "Mouse2", "🐁 MOUSE" },
            { "Rat", "🐀 RAT" },
            { "Hamster", "🐹 HAMSTER FACE" },
            { "Rabbit", "🐰 RABBIT FACE" },
            { "Rabbit2", "🐇 RABBIT" },
            { "Hedgehog", "🦔 HEDGEHOG" },
            { "Bat", "🦇 BAT" },
            { "Bear", "🐻 BEAR FACE" },
            { "Koala", "🐨 KOALA" },
            { "PandaFace", "🐼 PANDA FACE" },
            { "Feet", "🐾 PAW PRINTS" },
            { "Turkey", "🦃 TURKEY" },
            { "Chicken", "🐔 CHICKEN" },
            { "Rooster", "🐓 ROOSTER" },
            { "HatchingChick", "🐣 HATCHING CHICK" },
            { "BabyChick", "🐤 BABY CHICK" },
            { "HatchedChick", "🐥 FRONT-FACING BABY CHICK" },
            { "Bird", "🐦 BIRD" },
            { "Penguin", "🐧 PENGUIN" },
            { "Eagle", "🦅 EAGLE" },
            { "Duck", "🦆 DUCK" },
            { "Owl", "🦉 OWL" },
            { "Frog", "🐸 FROG FACE" },
            { "Crocodile", "🐊 CROCODILE" },
            { "Turtle", "🐢 TURTLE" },
            { "Lizard", "🦎 LIZARD" },
            { "Snake", "🐍 SNAKE" },
            { "DragonFace", "🐲 DRAGON FACE" },
            { "Dragon", "🐉 DRAGON" },
            { "Sauropod", "🦕 SAUROPOD" },
            { "TRex", "🦖 T-REX" },
            { "Whale", "🐳 SPOUTING WHALE" },
            { "Whale2", "🐋 WHALE" },
            { "Dolphin", "🐬 DOLPHIN" },
            { "Fish", "🐟 FISH" },
            { "TropicalFish", "🐠 TROPICAL FISH" },
            { "Blowfish", "🐡 BLOWFISH" },
            { "Shark", "🦈 SHARK" },
            { "Octopus", "🐙 OCTOPUS" },
            { "Shell", "🐚 SPIRAL SHELL" },
            { "Crab", "🦀 CRAB" },
            { "Shrimp", "🦐 SHRIMP" },
            { "Squid", "🦑 SQUID" },
            { "Snail", "🐌 SNAIL" },
            { "Butterfly", "🦋 BUTTERFLY" },
            { "Bug", "🐛 BUG" },
            { "Ant", "🐜 ANT" },
            { "Bee", "🐝 HONEYBEE" },
            { "Beetle", "🐞 LADY BEETLE" },
            { "Cricket", "🦗 CRICKET" },
            { "Scorpion", "🦂 SCORPION" },
            { "Bouquet", "💐 BOUQUET" },
            { "CherryBlossom", "🌸 CHERRY BLOSSOM" },
            { "WhiteFlower", "💮 WHITE FLOWER" },
            { "Rose", "🌹 ROSE" },
            { "WiltedFlower", "🥀 WILTED FLOWER" },
            { "Hibiscus", "🌺 HIBISCUS" },
            { "Sunflower", "🌻 SUNFLOWER" },
            { "Blossom", "🌼 BLOSSOM" },
            { "Tulip", "🌷 TULIP" },
            { "Seedling", "🌱 SEEDLING" },
            { "EvergreenTree", "🌲 EVERGREEN TREE" },
            { "DeciduousTree", "🌳 DECIDUOUS TREE" },
            { "PalmTree", "🌴 PALM TREE" },
            { "Cactus", "🌵 CACTUS" },
            { "EarOfRice", "🌾 EAR OF RICE" },
            { "Herb", "🌿 HERB" },
            { "FourLeafClover", "🍀 FOUR LEAF CLOVER" },
            { "MapleLeaf", "🍁 MAPLE LEAF" },
            { "FallenLeaf", "🍂 FALLEN LEAF" },
            { "Leaves", "🍃 LEAF FLUTTERING IN WIND" },
            { "Grapes", "🍇 GRAPES" },
            { "Melon", "🍈 MELON" },
            { "Watermelon", "🍉 WATERMELON" },
            { "Tangerine", "🍊 TANGERINE" },
            { "Lemon", "🍋 LEMON" },
            { "Banana", "🍌 BANANA" },
            { "Pineapple", "🍍 PINEAPPLE" },
            { "Apple", "🍎 RED APPLE" },
            { "GreenApple", "🍏 GREEN APPLE" },
            { "Pear", "🍐 PEAR" },
            { "Peach", "🍑 PEACH" },
            { "Cherries", "🍒 CHERRIES" },
            { "Strawberry", "🍓 STRAWBERRY" },
            { "Kiwifruit", "🥝 KIWIFRUIT" },
            { "Tomato", "🍅 TOMATO" },
            { "Coconut", "🥥 COCONUT" },
            { "Avocado", "🥑 AVOCADO" },
            { "Eggplant", "🍆 AUBERGINE" },
            { "Potato", "🥔 POTATO" },
            { "Carrot", "🥕 CARROT" },
            { "Corn", "🌽 EAR OF MAIZE" },
            { "Cucumber", "🥒 CUCUMBER" },
            { "Broccoli", "🥦 BROCCOLI" },
            { "Mushroom", "🍄 MUSHROOM" },
            { "Peanuts", "🥜 PEANUTS" },
            { "Chestnut", "🌰 CHESTNUT" },
            { "Bread", "🍞 BREAD" },
            { "Croissant", "🥐 CROISSANT" },
            { "BaguetteBread", "🥖 BAGUETTE BREAD" },
            { "Pretzel", "🥨 PRETZEL" },
            { "Pancakes", "🥞 PANCAKES" },
            { "CheeseWedge", "🧀 CHEESE WEDGE" },
            { "MeatOnBone", "🍖 MEAT ON BONE" },
            { "PoultryLeg", "🍗 POULTRY LEG" },
            { "CutOfMeat", "🥩 CUT OF MEAT" },
            { "Bacon", "🥓 BACON" },
            { "Hamburger", "🍔 HAMBURGER" },
            { "Fries", "🍟 FRENCH FRIES" },
            { "Pizza", "🍕 SLICE OF PIZZA" },
            { "Hotdog", "🌭 HOT DOG" },
            { "Sandwich", "🥪 SANDWICH" },
            { "Taco", "🌮 TACO" },
            { "Burrito", "🌯 BURRITO" },
            { "StuffedFlatbread", "🥙 STUFFED FLATBREAD" },
            { "Egg", "🥚 EGG" },
            { "FriedEgg", "🍳 COOKING" },
            { "ShallowPanOfFood", "🥘 SHALLOW PAN OF FOOD" },
            { "Stew", "🍲 POT OF FOOD" },
            { "BowlWithSpoon", "🥣 BOWL WITH SPOON" },
            { "GreenSalad", "🥗 GREEN SALAD" },
            { "Popcorn", "🍿 POPCORN" },
            { "CannedFood", "🥫 CANNED FOOD" },
            { "Bento", "🍱 BENTO BOX" },
            { "RiceCracker", "🍘 RICE CRACKER" },
            { "RiceBall", "🍙 RICE BALL" },
            { "Rice", "🍚 COOKED RICE" },
            { "Curry", "🍛 CURRY AND RICE" },
            { "Ramen", "🍜 STEAMING BOWL" },
            { "Spaghetti", "🍝 SPAGHETTI" },
            { "SweetPotato", "🍠 ROASTED SWEET POTATO" },
            { "Oden", "🍢 ODEN" },
            { "Sushi", "🍣 SUSHI" },
            { "FriedShrimp", "🍤 FRIED SHRIMP" },
            { "FishCake", "🍥 FISH CAKE WITH SWIRL DESIGN" },
            { "Dango", "🍡 DANGO" },
            { "Dumpling", "🥟 DUMPLING" },
            { "FortuneCookie", "🥠 FORTUNE COOKIE" },
            { "TakeoutBox", "🥡 TAKEOUT BOX" },
            { "Icecream", "🍦 SOFT ICE CREAM" },
            { "ShavedIce", "🍧 SHAVED ICE" },
            { "IceCream", "🍨 ICE CREAM" },
            { "Doughnut", "🍩 DOUGHNUT" },
            { "Cookie", "🍪 COOKIE" },
            { "Birthday", "🎂 BIRTHDAY CAKE" },
            { "Cake", "🍰 SHORTCAKE" },
            { "Pie", "🥧 PIE" },
            { "ChocolateBar", "🍫 CHOCOLATE BAR" },
            { "Candy", "🍬 CANDY" },
            { "Lollipop", "🍭 LOLLIPOP" },
            { "Custard", "🍮 CUSTARD" },
            { "HoneyPot", "🍯 HONEY POT" },
            { "BabyBottle", "🍼 BABY BOTTLE" },
            { "GlassOfMilk", "🥛 GLASS OF MILK" },
            { "Coffee", "☕ HOT BEVERAGE" },
            { "Tea", "🍵 TEACUP WITHOUT HANDLE" },
            { "Sake", "🍶 SAKE BOTTLE AND CUP" },
            { "Champagne", "🍾 BOTTLE WITH POPPING CORK" },
            { "WineGlass", "🍷 WINE GLASS" },
            { "Cocktail", "🍸 COCKTAIL GLASS" },
            { "TropicalDrink", "🍹 TROPICAL DRINK" },
            { "Beer", "🍺 BEER MUG" },
            { "Beers", "🍻 CLINKING BEER MUGS" },
            { "ClinkingGlasses", "🥂 CLINKING GLASSES" },
            { "TumblerGlass", "🥃 TUMBLER GLASS" },
            { "CupWithStraw", "🥤 CUP WITH STRAW" },
            { "Chopsticks", "🥢 CHOPSTICKS" },
            { "ForkAndKnife", "🍴 FORK AND KNIFE" },
            { "Spoon", "🥄 SPOON" },
            { "Hocho", "🔪 HOCHO" },
            { "Amphora", "🏺 AMPHORA" },
            { "EarthAfrica", "🌍 EARTH GLOBE EUROPE-AFRICA" },
            { "EarthAmericas", "🌎 EARTH GLOBE AMERICAS" },
            { "EarthAsia", "🌏 EARTH GLOBE ASIA-AUSTRALIA" },
            { "GlobeWithMeridians", "🌐 GLOBE WITH MERIDIANS" },
            { "Japan", "🗾 SILHOUETTE OF JAPAN" },
            { "Volcano", "🌋 VOLCANO" },
            { "MountFuji", "🗻 MOUNT FUJI" },
            { "House", "🏠 HOUSE BUILDING" },
            { "HouseWithGarden", "🏡 HOUSE WITH GARDEN" },
            { "Office", "🏢 OFFICE BUILDING" },
            { "PostOffice", "🏣 JAPANESE POST OFFICE" },
            { "EuropeanPostOffice", "🏤 EUROPEAN POST OFFICE" },
            { "Hospital", "🏥 HOSPITAL" },
            { "Bank", "🏦 BANK" },
            { "Hotel", "🏨 HOTEL" },
            { "LoveHotel", "🏩 LOVE HOTEL" },
            { "ConvenienceStore", "🏪 CONVENIENCE STORE" },
            { "School", "🏫 SCHOOL" },
            { "DepartmentStore", "🏬 DEPARTMENT STORE" },
            { "Factory", "🏭 FACTORY" },
            { "JapaneseCastle", "🏯 JAPANESE CASTLE" },
            { "EuropeanCastle", "🏰 EUROPEAN CASTLE" },
            { "Wedding", "💒 WEDDING" },
            { "TokyoTower", "🗼 TOKYO TOWER" },
            { "StatueOfLiberty", "🗽 STATUE OF LIBERTY" },
            { "Church", "⛪ CHURCH" },
            { "Mosque", "🕌 MOSQUE" },
            { "Synagogue", "🕍 SYNAGOGUE" },
            { "Kaaba", "🕋 KAABA" },
            { "Fountain", "⛲ FOUNTAIN" },
            { "Tent", "⛺ TENT" },
            { "Foggy", "🌁 FOGGY" },
            { "NightWithStars", "🌃 NIGHT WITH STARS" },
            { "SunriseOverMountains", "🌄 SUNRISE OVER MOUNTAINS" },
            { "Sunrise", "🌅 SUNRISE" },
            { "CitySunset", "🌆 CITYSCAPE AT DUSK" },
            { "CitySunrise", "🌇 SUNSET OVER BUILDINGS" },
            { "BridgeAtNight", "🌉 BRIDGE AT NIGHT" },
            { "Hotsprings", "♨️ HOT SPRINGS" },
            { "MilkyWay", "🌌 MILKY WAY" },
            { "CarouselHorse", "🎠 CAROUSEL HORSE" },
            { "FerrisWheel", "🎡 FERRIS WHEEL" },
            { "RollerCoaster", "🎢 ROLLER COASTER" },
            { "Barber", "💈 BARBER POLE" },
            { "CircusTent", "🎪 CIRCUS TENT" },
            { "SteamLocomotive", "🚂 STEAM LOCOMOTIVE" },
            { "RailwayCar", "🚃 RAILWAY CAR" },
            { "BullettrainSide", "🚄 HIGH-SPEED TRAIN" },
            { "BullettrainFront", "🚅 HIGH-SPEED TRAIN WITH BULLET NOSE" },
            { "Train2", "🚆 TRAIN" },
            { "Metro", "🚇 METRO" },
            { "LightRail", "🚈 LIGHT RAIL" },
            { "Station", "🚉 STATION" },
            { "Tram", "🚊 TRAM" },
            { "Monorail", "🚝 MONORAIL" },
            { "MountainRailway", "🚞 MOUNTAIN RAILWAY" },
            { "Train", "🚋 TRAM CAR" },
            { "Bus", "🚌 BUS" },
            { "OncomingBus", "🚍 ONCOMING BUS" },
            { "Trolleybus", "🚎 TROLLEYBUS" },
            { "Minibus", "🚐 MINIBUS" },
            { "Ambulance", "🚑 AMBULANCE" },
            { "FireEngine", "🚒 FIRE ENGINE" },
            { "PoliceCar", "🚓 POLICE CAR" },
            { "OncomingPoliceCar", "🚔 ONCOMING POLICE CAR" },
            { "Taxi", "🚕 TAXI" },
            { "OncomingTaxi", "🚖 ONCOMING TAXI" },
            { "Car", "🚗 AUTOMOBILE" },
            { "OncomingAutomobile", "🚘 ONCOMING AUTOMOBILE" },
            { "BlueCar", "🚙 RECREATIONAL VEHICLE" },
            { "Truck", "🚚 DELIVERY TRUCK" },
            { "ArticulatedLorry", "🚛 ARTICULATED LORRY" },
            { "Tractor", "🚜 TRACTOR" },
            { "Bike", "🚲 BICYCLE" },
            { "Scooter", "🛴 SCOOTER" },
            { "MotorScooter", "🛵 MOTOR SCOOTER" },
            { "Busstop", "🚏 BUS STOP" },
            { "Fuelpump", "⛽ FUEL PUMP" },
            { "RotatingLight", "🚨 POLICE CARS REVOLVING LIGHT" },
            { "TrafficLight", "🚥 HORIZONTAL TRAFFIC LIGHT" },
            { "VerticalTrafficLight", "🚦 VERTICAL TRAFFIC LIGHT" },
            { "OctagonalSign", "🛑 OCTAGONAL SIGN" },
            { "Construction", "🚧 CONSTRUCTION SIGN" },
            { "Anchor", "⚓ ANCHOR" },
            { "Boat", "⛵ SAILBOAT" },
            { "Canoe", "🛶 CANOE" },
            { "Speedboat", "🚤 SPEEDBOAT" },
            { "Ship", "🚢 SHIP" },
            { "Airplane", "✈️ AIRPLANE" },
            { "AirplaneDeparture", "🛫 AIRPLANE DEPARTURE" },
            { "AirplaneArriving", "🛬 AIRPLANE ARRIVING" },
            { "Seat", "💺 SEAT" },
            { "Helicopter", "🚁 HELICOPTER" },
            { "SuspensionRailway", "🚟 SUSPENSION RAILWAY" },
            { "MountainCableway", "🚠 MOUNTAIN CABLEWAY" },
            { "AerialTramway", "🚡 AERIAL TRAMWAY" },
            { "Rocket", "🚀 ROCKET" },
            { "FlyingSaucer", "🛸 FLYING SAUCER" },
            { "Hourglass", "⌛ HOURGLASS" },
            { "HourglassFlowingSand", "⏳ HOURGLASS WITH FLOWING SAND" },
            { "Watch", "⌚ WATCH" },
            { "AlarmClock", "⏰ ALARM CLOCK" },
            { "Clock12", "🕛 CLOCK FACE TWELVE OCLOCK" },
            { "Clock1230", "🕧 CLOCK FACE TWELVE-THIRTY" },
            { "Clock1", "🕐 CLOCK FACE ONE OCLOCK" },
            { "Clock130", "🕜 CLOCK FACE ONE-THIRTY" },
            { "Clock2", "🕑 CLOCK FACE TWO OCLOCK" },
            { "Clock230", "🕝 CLOCK FACE TWO-THIRTY" },
            { "Clock3", "🕒 CLOCK FACE THREE OCLOCK" },
            { "Clock330", "🕞 CLOCK FACE THREE-THIRTY" },
            { "Clock4", "🕓 CLOCK FACE FOUR OCLOCK" },
            { "Clock430", "🕟 CLOCK FACE FOUR-THIRTY" },
            { "Clock5", "🕔 CLOCK FACE FIVE OCLOCK" },
            { "Clock530", "🕠 CLOCK FACE FIVE-THIRTY" },
            { "Clock6", "🕕 CLOCK FACE SIX OCLOCK" },
            { "Clock630", "🕡 CLOCK FACE SIX-THIRTY" },
            { "Clock7", "🕖 CLOCK FACE SEVEN OCLOCK" },
            { "Clock730", "🕢 CLOCK FACE SEVEN-THIRTY" },
            { "Clock8", "🕗 CLOCK FACE EIGHT OCLOCK" },
            { "Clock830", "🕣 CLOCK FACE EIGHT-THIRTY" },
            { "Clock9", "🕘 CLOCK FACE NINE OCLOCK" },
            { "Clock930", "🕤 CLOCK FACE NINE-THIRTY" },
            { "Clock10", "🕙 CLOCK FACE TEN OCLOCK" },
            { "Clock1030", "🕥 CLOCK FACE TEN-THIRTY" },
            { "Clock11", "🕚 CLOCK FACE ELEVEN OCLOCK" },
            { "Clock1130", "🕦 CLOCK FACE ELEVEN-THIRTY" },
            { "NewMoon", "🌑 NEW MOON SYMBOL" },
            { "WaxingCrescentMoon", "🌒 WAXING CRESCENT MOON SYMBOL" },
            { "FirstQuarterMoon", "🌓 FIRST QUARTER MOON SYMBOL" },
            { "Moon", "🌔 WAXING GIBBOUS MOON SYMBOL" },
            { "FullMoon", "🌕 FULL MOON SYMBOL" },
            { "WaningGibbousMoon", "🌖 WANING GIBBOUS MOON SYMBOL" },
            { "LastQuarterMoon", "🌗 LAST QUARTER MOON SYMBOL" },
            { "WaningCrescentMoon", "🌘 WANING CRESCENT MOON SYMBOL" },
            { "CrescentMoon", "🌙 CRESCENT MOON" },
            { "NewMoonWithFace", "🌚 NEW MOON WITH FACE" },
            { "FirstQuarterMoonWithFace", "🌛 FIRST QUARTER MOON WITH FACE" },
            { "LastQuarterMoonWithFace", "🌜 LAST QUARTER MOON WITH FACE" },
            { "Sunny", "☀️ BLACK SUN WITH RAYS" },
            { "FullMoonWithFace", "🌝 FULL MOON WITH FACE" },
            { "SunWithFace", "🌞 SUN WITH FACE" },
            { "Star", "⭐ WHITE MEDIUM STAR" },
            { "Star2", "🌟 GLOWING STAR" },
            { "Stars", "🌠 SHOOTING STAR" },
            { "Cloud", "☁️ CLOUD" },
            { "PartlySunny", "⛅ SUN BEHIND CLOUD" },
            { "Cyclone", "🌀 CYCLONE" },
            { "Rainbow", "🌈 RAINBOW" },
            { "ClosedUmbrella", "🌂 CLOSED UMBRELLA" },
            { "UmbrellaWithRainDrops", "☔ UMBRELLA WITH RAIN DROPS" },
            { "Zap", "⚡ HIGH VOLTAGE SIGN" },
            { "Snowflake", "❄️ SNOWFLAKE" },
            { "SnowmanWithoutSnow", "⛄ SNOWMAN WITHOUT SNOW" },
            { "Fire", "🔥 FIRE" },
            { "Droplet", "💧 DROPLET" },
            { "Ocean", "🌊 WATER WAVE" },
            { "JackOLantern", "🎃 JACK-O-LANTERN" },
            { "ChristmasTree", "🎄 CHRISTMAS TREE" },
            { "Fireworks", "🎆 FIREWORKS" },
            { "Sparkler", "🎇 FIREWORK SPARKLER" },
            { "Sparkles", "✨ SPARKLES" },
            { "Balloon", "🎈 BALLOON" },
            { "Tada", "🎉 PARTY POPPER" },
            { "ConfettiBall", "🎊 CONFETTI BALL" },
            { "TanabataTree", "🎋 TANABATA TREE" },
            { "Bamboo", "🎍 PINE DECORATION" },
            { "Dolls", "🎎 JAPANESE DOLLS" },
            { "Flags", "🎏 CARP STREAMER" },
            { "WindChime", "🎐 WIND CHIME" },
            { "RiceScene", "🎑 MOON VIEWING CEREMONY" },
            { "Ribbon", "🎀 RIBBON" },
            { "Gift", "🎁 WRAPPED PRESENT" },
            { "Ticket", "🎫 TICKET" },
            { "Trophy", "🏆 TROPHY" },
            { "SportsMedal", "🏅 SPORTS MEDAL" },
            { "FirstPlaceMedal", "🥇 FIRST PLACE MEDAL" },
            { "SecondPlaceMedal", "🥈 SECOND PLACE MEDAL" },
            { "ThirdPlaceMedal", "🥉 THIRD PLACE MEDAL" },
            { "Soccer", "⚽ SOCCER BALL" },
            { "Baseball", "⚾ BASEBALL" },
            { "Basketball", "🏀 BASKETBALL AND HOOP" },
            { "Volleyball", "🏐 VOLLEYBALL" },
            { "Football", "🏈 AMERICAN FOOTBALL" },
            { "RugbyFootball", "🏉 RUGBY FOOTBALL" },
            { "Tennis", "🎾 TENNIS RACQUET AND BALL" },
            { "Bowling", "🎳 BOWLING" },
            { "CricketBatAndBall", "🏏 CRICKET BAT AND BALL" },
            { "FieldHockeyStickAndBall", "🏑 FIELD HOCKEY STICK AND BALL" },
            { "IceHockeyStickAndPuck", "🏒 ICE HOCKEY STICK AND PUCK" },
            { "TableTennisPaddleAndBall", "🏓 TABLE TENNIS PADDLE AND BALL" },
            { "BadmintonRacquetAndShuttlecock", "🏸 BADMINTON RACQUET AND SHUTTLECOCK" },
            { "BoxingGlove", "🥊 BOXING GLOVE" },
            { "MartialArtsUniform", "🥋 MARTIAL ARTS UNIFORM" },
            { "GoalNet", "🥅 GOAL NET" },
            { "Golf", "⛳ FLAG IN HOLE" },
            { "FishingPoleAndFish", "🎣 FISHING POLE AND FISH" },
            { "RunningShirtWithSash", "🎽 RUNNING SHIRT WITH SASH" },
            { "Ski", "🎿 SKI AND SKI BOOT" },
            { "Sled", "🛷 SLED" },
            { "CurlingStone", "🥌 CURLING STONE" },
            { "Dart", "🎯 DIRECT HIT" },
            { "EightBall", "🎱 BILLIARDS" },
            { "CrystalBall", "🔮 CRYSTAL BALL" },
            { "VideoGame", "🎮 VIDEO GAME" },
            { "SlotMachine", "🎰 SLOT MACHINE" },
            { "GameDie", "🎲 GAME DIE" },
            { "Spades", "♠️ BLACK SPADE SUIT" },
            { "Hearts", "♥️ BLACK HEART SUIT" },
            { "Diamonds", "♦️ BLACK DIAMOND SUIT" },
            { "Clubs", "♣️ BLACK CLUB SUIT" },
            { "BlackJoker", "🃏 PLAYING CARD BLACK JOKER" },
            { "Mahjong", "🀄 MAHJONG TILE RED DRAGON" },
            { "FlowerPlayingCards", "🎴 FLOWER PLAYING CARDS" },
            { "PerformingArts", "🎭 PERFORMING ARTS" },
            { "Art", "🎨 ARTIST PALETTE" },
            { "Mute", "🔇 SPEAKER WITH CANCELLATION STROKE" },
            { "Speaker", "🔈 SPEAKER" },
            { "Sound", "🔉 SPEAKER WITH ONE SOUND WAVE" },
            { "LoudSound", "🔊 SPEAKER WITH THREE SOUND WAVES" },
            { "Loudspeaker", "📢 PUBLIC ADDRESS LOUDSPEAKER" },
            { "Mega", "📣 CHEERING MEGAPHONE" },
            { "PostalHorn", "📯 POSTAL HORN" },
            { "Bell", "🔔 BELL" },
            { "NoBell", "🔕 BELL WITH CANCELLATION STROKE" },
            { "MusicalScore", "🎼 MUSICAL SCORE" },
            { "MusicalNote", "🎵 MUSICAL NOTE" },
            { "Notes", "🎶 MULTIPLE MUSICAL NOTES" },
            { "Microphone", "🎤 MICROPHONE" },
            { "Headphones", "🎧 HEADPHONE" },
            { "Radio", "📻 RADIO" },
            { "Saxophone", "🎷 SAXOPHONE" },
            { "Guitar", "🎸 GUITAR" },
            { "MusicalKeyboard", "🎹 MUSICAL KEYBOARD" },
            { "Trumpet", "🎺 TRUMPET" },
            { "Violin", "🎻 VIOLIN" },
            { "DrumWithDrumsticks", "🥁 DRUM WITH DRUMSTICKS" },
            { "Iphone", "📱 MOBILE PHONE" },
            { "Calling", "📲 MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT" },
            { "Phone", "☎️ BLACK TELEPHONE" },
            { "TelephoneReceiver", "📞 TELEPHONE RECEIVER" },
            { "Pager", "📟 PAGER" },
            { "Fax", "📠 FAX MACHINE" },
            { "Battery", "🔋 BATTERY" },
            { "ElectricPlug", "🔌 ELECTRIC PLUG" },
            { "Computer", "💻 PERSONAL COMPUTER" },
            { "Minidisc", "💽 MINIDISC" },
            { "FloppyDisk", "💾 FLOPPY DISK" },
            { "Cd", "💿 OPTICAL DISC" },
            { "Dvd", "📀 DVD" },
            { "MovieCamera", "🎥 MOVIE CAMERA" },
            { "Clapper", "🎬 CLAPPER BOARD" },
            { "Tv", "📺 TELEVISION" },
            { "Camera", "📷 CAMERA" },
            { "CameraWithFlash", "📸 CAMERA WITH FLASH" },
            { "VideoCamera", "📹 VIDEO CAMERA" },
            { "Vhs", "📼 VIDEOCASSETTE" },
            { "Mag", "🔍 LEFT-POINTING MAGNIFYING GLASS" },
            { "MagRight", "🔎 RIGHT-POINTING MAGNIFYING GLASS" },
            { "Bulb", "💡 ELECTRIC LIGHT BULB" },
            { "Flashlight", "🔦 ELECTRIC TORCH" },
            { "IzakayaLantern", "🏮 IZAKAYA LANTERN" },
            { "NotebookWithDecorativeCover", "📔 NOTEBOOK WITH DECORATIVE COVER" },
            { "ClosedBook", "📕 CLOSED BOOK" },
            { "Book", "📖 OPEN BOOK" },
            { "GreenBook", "📗 GREEN BOOK" },
            { "BlueBook", "📘 BLUE BOOK" },
            { "OrangeBook", "📙 ORANGE BOOK" },
            { "Books", "📚 BOOKS" },
            { "Notebook", "📓 NOTEBOOK" },
            { "Ledger", "📒 LEDGER" },
            { "PageWithCurl", "📃 PAGE WITH CURL" },
            { "Scroll", "📜 SCROLL" },
            { "PageFacingUp", "📄 PAGE FACING UP" },
            { "Newspaper", "📰 NEWSPAPER" },
            { "BookmarkTabs", "📑 BOOKMARK TABS" },
            { "Bookmark", "🔖 BOOKMARK" },
            { "Moneybag", "💰 MONEY BAG" },
            { "Yen", "💴 BANKNOTE WITH YEN SIGN" },
            { "Dollar", "💵 BANKNOTE WITH DOLLAR SIGN" },
            { "Euro", "💶 BANKNOTE WITH EURO SIGN" },
            { "Pound", "💷 BANKNOTE WITH POUND SIGN" },
            { "MoneyWithWings", "💸 MONEY WITH WINGS" },
            { "CreditCard", "💳 CREDIT CARD" },
            { "Chart", "💹 CHART WITH UPWARDS TREND AND YEN SIGN" },
            { "CurrencyExchange", "💱 CURRENCY EXCHANGE" },
            { "HeavyDollarSign", "💲 HEAVY DOLLAR SIGN" },
            { "Email", "✉️ ENVELOPE" },
            { "EMail", "📧 E-MAIL SYMBOL" },
            { "IncomingEnvelope", "📨 INCOMING ENVELOPE" },
            { "EnvelopeWithArrow", "📩 ENVELOPE WITH DOWNWARDS ARROW ABOVE" },
            { "OutboxTray", "📤 OUTBOX TRAY" },
            { "InboxTray", "📥 INBOX TRAY" },
            { "Package", "📦 PACKAGE" },
            { "Mailbox", "📫 CLOSED MAILBOX WITH RAISED FLAG" },
            { "MailboxClosed", "📪 CLOSED MAILBOX WITH LOWERED FLAG" },
            { "MailboxWithMail", "📬 OPEN MAILBOX WITH RAISED FLAG" },
            { "MailboxWithNoMail", "📭 OPEN MAILBOX WITH LOWERED FLAG" },
            { "Postbox", "📮 POSTBOX" },
            { "Pencil2", "✏️ PENCIL" },
            { "BlackNib", "✒️ BLACK NIB" },
            { "Memo", "📝 MEMO" },
            { "Briefcase", "💼 BRIEFCASE" },
            { "FileFolder", "📁 FILE FOLDER" },
            { "OpenFileFolder", "📂 OPEN FILE FOLDER" },
            { "Date", "📅 CALENDAR" },
            { "Calendar", "📆 TEAR-OFF CALENDAR" },
            { "CardIndex", "📇 CARD INDEX" },
            { "ChartWithUpwardsTrend", "📈 CHART WITH UPWARDS TREND" },
            { "ChartWithDownwardsTrend", "📉 CHART WITH DOWNWARDS TREND" },
            { "BarChart", "📊 BAR CHART" },
            { "Clipboard", "📋 CLIPBOARD" },
            { "Pushpin", "📌 PUSHPIN" },
            { "RoundPushpin", "📍 ROUND PUSHPIN" },
            { "Paperclip", "📎 PAPERCLIP" },
            { "StraightRuler", "📏 STRAIGHT RULER" },
            { "TriangularRuler", "📐 TRIANGULAR RULER" },
            { "Scissors", "✂️ BLACK SCISSORS" },
            { "Lock", "🔒 LOCK" },
            { "Unlock", "🔓 OPEN LOCK" },
            { "LockWithInkPen", "🔏 LOCK WITH INK PEN" },
            { "ClosedLockWithKey", "🔐 CLOSED LOCK WITH KEY" },
            { "Key", "🔑 KEY" },
            { "Hammer", "🔨 HAMMER" },
            { "Gun", "🔫 PISTOL" },
            { "BowAndArrow", "🏹 BOW AND ARROW" },
            { "Wrench", "🔧 WRENCH" },
            { "NutAndBolt", "🔩 NUT AND BOLT" },
            { "Link", "🔗 LINK SYMBOL" },
            { "Microscope", "🔬 MICROSCOPE" },
            { "Telescope", "🔭 TELESCOPE" },
            { "SatelliteAntenna", "📡 SATELLITE ANTENNA" },
            { "Syringe", "💉 SYRINGE" },
            { "Pill", "💊 PILL" },
            { "Door", "🚪 DOOR" },
            { "Toilet", "🚽 TOILET" },
            { "Shower", "🚿 SHOWER" },
            { "Bathtub", "🛁 BATHTUB" },
            { "ShoppingTrolley", "🛒 SHOPPING TROLLEY" },
            { "Smoking", "🚬 SMOKING SYMBOL" },
            { "Moyai", "🗿 MOYAI" },
            { "Atm", "🏧 AUTOMATED TELLER MACHINE" },
            { "PutLitterInItsPlace", "🚮 PUT LITTER IN ITS PLACE SYMBOL" },
            { "PotableWater", "🚰 POTABLE WATER SYMBOL" },
            { "Wheelchair", "♿ WHEELCHAIR SYMBOL" },
            { "Mens", "🚹 MENS SYMBOL" },
            { "Womens", "🚺 WOMENS SYMBOL" },
            { "Restroom", "🚻 RESTROOM" },
            { "BabySymbol", "🚼 BABY SYMBOL" },
            { "Wc", "🚾 WATER CLOSET" },
            { "PassportControl", "🛂 PASSPORT CONTROL" },
            { "Customs", "🛃 CUSTOMS" },
            { "BaggageClaim", "🛄 BAGGAGE CLAIM" },
            { "LeftLuggage", "🛅 LEFT LUGGAGE" },
            { "Warning", "⚠️ WARNING SIGN" },
            { "ChildrenCrossing", "🚸 CHILDREN CROSSING" },
            { "NoEntry", "⛔ NO ENTRY" },
            { "NoEntrySign", "🚫 NO ENTRY SIGN" },
            { "NoBicycles", "🚳 NO BICYCLES" },
            { "NoSmoking", "🚭 NO SMOKING SYMBOL" },
            { "DoNotLitter", "🚯 DO NOT LITTER SYMBOL" },
            { "NonPotableWater", "🚱 NON-POTABLE WATER SYMBOL" },
            { "NoPedestrians", "🚷 NO PEDESTRIANS" },
            { "NoMobilePhones", "📵 NO MOBILE PHONES" },
            { "Underage", "🔞 NO ONE UNDER EIGHTEEN SYMBOL" },
            { "ArrowUp", "⬆️ UPWARDS BLACK ARROW" },
            { "ArrowUpperRight", "↗️ NORTH EAST ARROW" },
            { "ArrowRight", "➡️ BLACK RIGHTWARDS ARROW" },
            { "ArrowLowerRight", "↘️ SOUTH EAST ARROW" },
            { "ArrowDown", "⬇️ DOWNWARDS BLACK ARROW" },
            { "ArrowLowerLeft", "↙️ SOUTH WEST ARROW" },
            { "ArrowLeft", "⬅️ LEFTWARDS BLACK ARROW" },
            { "ArrowUpperLeft", "↖️ NORTH WEST ARROW" },
            { "ArrowUpDown", "↕️ UP DOWN ARROW" },
            { "LeftRightArrow", "↔️ LEFT RIGHT ARROW" },
            { "LeftwardsArrowWithHook", "↩️ LEFTWARDS ARROW WITH HOOK" },
            { "ArrowRightHook", "↪️ RIGHTWARDS ARROW WITH HOOK" },
            { "ArrowHeadingUp", "⤴️ ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS" },
            { "ArrowHeadingDown", "⤵️ ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS" },
            { "ArrowsClockwise", "🔃 CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS" },
            { "ArrowsCounterclockwise", "🔄 ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS" },
            { "Back", "🔙 BACK WITH LEFTWARDS ARROW ABOVE" },
            { "End", "🔚 END WITH LEFTWARDS ARROW ABOVE" },
            { "On", "🔛 ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE" },
            { "Soon", "🔜 SOON WITH RIGHTWARDS ARROW ABOVE" },
            { "Top", "🔝 TOP WITH UPWARDS ARROW ABOVE" },
            { "PlaceOfWorship", "🛐 PLACE OF WORSHIP" },
            { "MenorahWithNineBranches", "🕎 MENORAH WITH NINE BRANCHES" },
            { "SixPointedStar", "🔯 SIX POINTED STAR WITH MIDDLE DOT" },
            { "Aries", "♈ ARIES" },
            { "Taurus", "♉ TAURUS" },
            { "Gemini", "♊ GEMINI" },
            { "Cancer", "♋ CANCER" },
            { "Leo", "♌ LEO" },
            { "Virgo", "♍ VIRGO" },
            { "Libra", "♎ LIBRA" },
            { "Scorpius", "♏ SCORPIUS" },
            { "Sagittarius", "♐ SAGITTARIUS" },
            { "Capricorn", "♑ CAPRICORN" },
            { "Aquarius", "♒ AQUARIUS" },
            { "Pisces", "♓ PISCES" },
            { "Ophiuchus", "⛎ OPHIUCHUS" },
            { "TwistedRightwardsArrows", "🔀 TWISTED RIGHTWARDS ARROWS" },
            { "Repeat", "🔁 CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS" },
            { "RepeatOne", "🔂 CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY" },
            { "ArrowForward", "▶️ BLACK RIGHT-POINTING TRIANGLE" },
            { "FastForward", "⏩ BLACK RIGHT-POINTING DOUBLE TRIANGLE" },
            { "ArrowBackward", "◀️ BLACK LEFT-POINTING TRIANGLE" },
            { "Rewind", "⏪ BLACK LEFT-POINTING DOUBLE TRIANGLE" },
            { "ArrowUpSmall", "🔼 UP-POINTING SMALL RED TRIANGLE" },
            { "ArrowDoubleUp", "⏫ BLACK UP-POINTING DOUBLE TRIANGLE" },
            { "ArrowDownSmall", "🔽 DOWN-POINTING SMALL RED TRIANGLE" },
            { "ArrowDoubleDown", "⏬ BLACK DOWN-POINTING DOUBLE TRIANGLE" },
            { "Cinema", "🎦 CINEMA" },
            { "LowBrightness", "🔅 LOW BRIGHTNESS SYMBOL" },
            { "HighBrightness", "🔆 HIGH BRIGHTNESS SYMBOL" },
            { "SignalStrength", "📶 ANTENNA WITH BARS" },
            { "VibrationMode", "📳 VIBRATION MODE" },
            { "MobilePhoneOff", "📴 MOBILE PHONE OFF" },
            { "Recycle", "♻️ BLACK UNIVERSAL RECYCLING SYMBOL" },
            { "Trident", "🔱 TRIDENT EMBLEM" },
            { "NameBadge", "📛 NAME BADGE" },
            { "Beginner", "🔰 JAPANESE SYMBOL FOR BEGINNER" },
            { "O", "⭕ HEAVY LARGE CIRCLE" },
            { "WhiteCheckMark", "✅ WHITE HEAVY CHECK MARK" },
            { "BallotBoxWithCheck", "☑️ BALLOT BOX WITH CHECK" },
            { "HeavyCheckMark", "✔️ HEAVY CHECK MARK" },
            { "HeavyMultiplicationX", "✖️ HEAVY MULTIPLICATION X" },
            { "X", "❌ CROSS MARK" },
            { "NegativeSquaredCrossMark", "❎ NEGATIVE SQUARED CROSS MARK" },
            { "HeavyPlusSign", "➕ HEAVY PLUS SIGN" },
            { "HeavyMinusSign", "➖ HEAVY MINUS SIGN" },
            { "HeavyDivisionSign", "➗ HEAVY DIVISION SIGN" },
            { "CurlyLoop", "➰ CURLY LOOP" },
            { "Loop", "➿ DOUBLE CURLY LOOP" },
            { "PartAlternationMark", "〽️ PART ALTERNATION MARK" },
            { "EightSpokedAsterisk", "✳️ EIGHT SPOKED ASTERISK" },
            { "EightPointedBlackStar", "✴️ EIGHT POINTED BLACK STAR" },
            { "Sparkle", "❇️ SPARKLE" },
            { "Bangbang", "‼️ DOUBLE EXCLAMATION MARK" },
            { "Interrobang", "⁉️ EXCLAMATION QUESTION MARK" },
            { "Question", "❓ BLACK QUESTION MARK ORNAMENT" },
            { "GreyQuestion", "❔ WHITE QUESTION MARK ORNAMENT" },
            { "GreyExclamation", "❕ WHITE EXCLAMATION MARK ORNAMENT" },
            { "Exclamation", "❗ HEAVY EXCLAMATION MARK SYMBOL" },
            { "WavyDash", "〰️ WAVY DASH" },
            { "Copyright", "©️ COPYRIGHT SIGN" },
            { "Registered", "®️ REGISTERED SIGN" },
            { "Tm", "™️ TRADE MARK SIGN" },
            { "Hash", "#️⃣ HASH KEY" },
            { "Zero", "0️⃣ KEYCAP 0" },
            { "One", "1️⃣ KEYCAP 1" },
            { "Two", "2️⃣ KEYCAP 2" },
            { "Three", "3️⃣ KEYCAP 3" },
            { "Four", "4️⃣ KEYCAP 4" },
            { "Five", "5️⃣ KEYCAP 5" },
            { "Six", "6️⃣ KEYCAP 6" },
            { "Seven", "7️⃣ KEYCAP 7" },
            { "Eight", "8️⃣ KEYCAP 8" },
            { "Nine", "9️⃣ KEYCAP 9" },
            { "KeycapTen", "🔟 KEYCAP TEN" },
            { "OneHundred", "💯 HUNDRED POINTS SYMBOL" },
            { "CapitalAbcd", "🔠 INPUT SYMBOL FOR LATIN CAPITAL LETTERS" },
            { "Abcd", "🔡 INPUT SYMBOL FOR LATIN SMALL LETTERS" },
            { "OneTwoThreeFour", "🔢 INPUT SYMBOL FOR NUMBERS" },
            { "Symbols", "🔣 INPUT SYMBOL FOR SYMBOLS" },
            { "Abc", "🔤 INPUT SYMBOL FOR LATIN LETTERS" },
            { "A", "🅰️ NEGATIVE SQUARED LATIN CAPITAL LETTER A" },
            { "Ab", "🆎 NEGATIVE SQUARED AB" },
            { "B", "🅱️ NEGATIVE SQUARED LATIN CAPITAL LETTER B" },
            { "Cl", "🆑 SQUARED CL" },
            { "Cool", "🆒 SQUARED COOL" },
            { "Free", "🆓 SQUARED FREE" },
            { "InformationSource", "ℹ️ INFORMATION SOURCE" },
            { "Id", "🆔 SQUARED ID" },
            { "M", "Ⓜ️ CIRCLED LATIN CAPITAL LETTER M" },
            { "New", "🆕 SQUARED NEW" },
            { "Ng", "🆖 SQUARED NG" },
            { "O2", "🅾️ NEGATIVE SQUARED LATIN CAPITAL LETTER O" },
            { "Ok", "🆗 SQUARED OK" },
            { "Parking", "🅿️ NEGATIVE SQUARED LATIN CAPITAL LETTER P" },
            { "Sos", "🆘 SQUARED SOS" },
            { "Up", "🆙 SQUARED UP WITH EXCLAMATION MARK" },
            { "Vs", "🆚 SQUARED VS" },
            { "Koko", "🈁 SQUARED KATAKANA KOKO" },
            { "Sa", "🈂️ SQUARED KATAKANA SA" },
            { "U6708", "🈷️ SQUARED CJK UNIFIED IDEOGRAPH-6708" },
            { "U6709", "🈶 SQUARED CJK UNIFIED IDEOGRAPH-6709" },
            { "U6307", "🈯 SQUARED CJK UNIFIED IDEOGRAPH-6307" },
            { "IdeographAdvantage", "🉐 CIRCLED IDEOGRAPH ADVANTAGE" },
            { "U5272", "🈹 SQUARED CJK UNIFIED IDEOGRAPH-5272" },
            { "U7121", "🈚 SQUARED CJK UNIFIED IDEOGRAPH-7121" },
            { "U7981", "🈲 SQUARED CJK UNIFIED IDEOGRAPH-7981" },
            { "Accept", "🉑 CIRCLED IDEOGRAPH ACCEPT" },
            { "U7533", "🈸 SQUARED CJK UNIFIED IDEOGRAPH-7533" },
            { "U5408", "🈴 SQUARED CJK UNIFIED IDEOGRAPH-5408" },
            { "U7a7a", "🈳 SQUARED CJK UNIFIED IDEOGRAPH-7A7A" },
            { "Congratulations", "㊗️ CIRCLED IDEOGRAPH CONGRATULATION" },
            { "Secret", "㊙️ CIRCLED IDEOGRAPH SECRET" },
            { "U55b6", "🈺 SQUARED CJK UNIFIED IDEOGRAPH-55B6" },
            { "U6e80", "🈵 SQUARED CJK UNIFIED IDEOGRAPH-6E80" },
            { "RedCircle", "🔴 LARGE RED CIRCLE" },
            { "LargeBlueCircle", "🔵 LARGE BLUE CIRCLE" },
            { "WhiteCircle", "⚪ MEDIUM WHITE CIRCLE" },
            { "BlackCircle", "⚫ MEDIUM BLACK CIRCLE" },
            { "WhiteLargeSquare", "⬜ WHITE LARGE SQUARE" },
            { "BlackLargeSquare", "⬛ BLACK LARGE SQUARE" },
            { "BlackMediumSquare", "◼️ BLACK MEDIUM SQUARE" },
            { "WhiteMediumSquare", "◻️ WHITE MEDIUM SQUARE" },
            { "WhiteMediumSmallSquare", "◽ WHITE MEDIUM SMALL SQUARE" },
            { "BlackMediumSmallSquare", "◾ BLACK MEDIUM SMALL SQUARE" },
            { "WhiteSmallSquare", "▫️ WHITE SMALL SQUARE" },
            { "BlackSmallSquare", "▪️ BLACK SMALL SQUARE" },
            { "LargeOrangeDiamond", "🔶 LARGE ORANGE DIAMOND" },
            { "LargeBlueDiamond", "🔷 LARGE BLUE DIAMOND" },
            { "SmallOrangeDiamond", "🔸 SMALL ORANGE DIAMOND" },
            { "SmallBlueDiamond", "🔹 SMALL BLUE DIAMOND" },
            { "SmallRedTriangle", "🔺 UP-POINTING RED TRIANGLE" },
            { "SmallRedTriangleDown", "🔻 DOWN-POINTING RED TRIANGLE" },
            { "DiamondShapeWithADotInside", "💠 DIAMOND SHAPE WITH A DOT INSIDE" },
            { "RadioButton", "🔘 RADIO BUTTON" },
            { "BlackSquareButton", "🔲 BLACK SQUARE BUTTON" },
            { "WhiteSquareButton", "🔳 WHITE SQUARE BUTTON" },
            { "CheckeredFlag", "🏁 CHEQUERED FLAG" },
            { "TriangularFlagOnPost", "🚩 TRIANGULAR FLAG ON POST" },
            { "CrossedFlags", "🎌 CROSSED FLAGS" },
            { "WavingBlackFlag", "🏴 WAVING BLACK FLAG" },
            { "FlagAc", "🇦🇨 Ascension Island Flag" },
            { "FlagAd", "🇦🇩 Andorra Flag" },
            { "FlagAe", "🇦🇪 United Arab Emirates Flag" },
            { "FlagAf", "🇦🇫 Afghanistan Flag" },
            { "FlagAg", "🇦🇬 Antigua & Barbuda Flag" },
            { "FlagAi", "🇦🇮 Anguilla Flag" },
            { "FlagAl", "🇦🇱 Albania Flag" },
            { "FlagAm", "🇦🇲 Armenia Flag" },
            { "FlagAo", "🇦🇴 Angola Flag" },
            { "FlagAq", "🇦🇶 Antarctica Flag" },
            { "FlagAr", "🇦🇷 Argentina Flag" },
            { "FlagAs", "🇦🇸 American Samoa Flag" },
            { "FlagAt", "🇦🇹 Austria Flag" },
            { "FlagAu", "🇦🇺 Australia Flag" },
            { "FlagAw", "🇦🇼 Aruba Flag" },
            { "FlagAx", "🇦🇽 Åland Islands Flag" },
            { "FlagAz", "🇦🇿 Azerbaijan Flag" },
            { "FlagBa", "🇧🇦 Bosnia & Herzegovina Flag" },
            { "FlagBb", "🇧🇧 Barbados Flag" },
            { "FlagBd", "🇧🇩 Bangladesh Flag" },
            { "FlagBe", "🇧🇪 Belgium Flag" },
            { "FlagBf", "🇧🇫 Burkina Faso Flag" },
            { "FlagBg", "🇧🇬 Bulgaria Flag" },
            { "FlagBh", "🇧🇭 Bahrain Flag" },
            { "FlagBi", "🇧🇮 Burundi Flag" },
            { "FlagBj", "🇧🇯 Benin Flag" },
            { "FlagBl", "🇧🇱 St. Barthélemy Flag" },
            { "FlagBm", "🇧🇲 Bermuda Flag" },
            { "FlagBn", "🇧🇳 Brunei Flag" },
            { "FlagBo", "🇧🇴 Bolivia Flag" },
            { "FlagBq", "🇧🇶 Caribbean Netherlands Flag" },
            { "FlagBr", "🇧🇷 Brazil Flag" },
            { "FlagBs", "🇧🇸 Bahamas Flag" },
            { "FlagBt", "🇧🇹 Bhutan Flag" },
            { "FlagBv", "🇧🇻 Bouvet Island Flag" },
            { "FlagBw", "🇧🇼 Botswana Flag" },
            { "FlagBy", "🇧🇾 Belarus Flag" },
            { "FlagBz", "🇧🇿 Belize Flag" },
            { "FlagCa", "🇨🇦 Canada Flag" },
            { "FlagCc", "🇨🇨 Cocos (Keeling) Islands Flag" },
            { "FlagCd", "🇨🇩 Congo - Kinshasa Flag" },
            { "FlagCf", "🇨🇫 Central African Republic Flag" },
            { "FlagCg", "🇨🇬 Congo - Brazzaville Flag" },
            { "FlagCh", "🇨🇭 Switzerland Flag" },
            { "FlagCi", "🇨🇮 Côte d’Ivoire Flag" },
            { "FlagCk", "🇨🇰 Cook Islands Flag" },
            { "FlagCl", "🇨🇱 Chile Flag" },
            { "FlagCm", "🇨🇲 Cameroon Flag" },
            { "Cn", "🇨🇳 China Flag" },
            { "FlagCo", "🇨🇴 Colombia Flag" },
            { "FlagCp", "🇨🇵 Clipperton Island Flag" },
            { "FlagCr", "🇨🇷 Costa Rica Flag" },
            { "FlagCu", "🇨🇺 Cuba Flag" },
            { "FlagCv", "🇨🇻 Cape Verde Flag" },
            { "FlagCw", "🇨🇼 Curaçao Flag" },
            { "FlagCx", "🇨🇽 Christmas Island Flag" },
            { "FlagCy", "🇨🇾 Cyprus Flag" },
            { "FlagCz", "🇨🇿 Czechia Flag" },
            { "De", "🇩🇪 Germany Flag" },
            { "FlagDg", "🇩🇬 Diego Garcia Flag" },
            { "FlagDj", "🇩🇯 Djibouti Flag" },
            { "FlagDk", "🇩🇰 Denmark Flag" },
            { "FlagDm", "🇩🇲 Dominica Flag" },
            { "FlagDo", "🇩🇴 Dominican Republic Flag" },
            { "FlagDz", "🇩🇿 Algeria Flag" },
            { "FlagEa", "🇪🇦 Ceuta & Melilla Flag" },
            { "FlagEc", "🇪🇨 Ecuador Flag" },
            { "FlagEe", "🇪🇪 Estonia Flag" },
            { "FlagEg", "🇪🇬 Egypt Flag" },
            { "FlagEh", "🇪🇭 Western Sahara Flag" },
            { "FlagEr", "🇪🇷 Eritrea Flag" },
            { "Es", "🇪🇸 Spain Flag" },
            { "FlagEt", "🇪🇹 Ethiopia Flag" },
            { "FlagEu", "🇪🇺 European Union Flag" },
            { "FlagFi", "🇫🇮 Finland Flag" },
            { "FlagFj", "🇫🇯 Fiji Flag" },
            { "FlagFk", "🇫🇰 Falkland Islands Flag" },
            { "FlagFm", "🇫🇲 Micronesia Flag" },
            { "FlagFo", "🇫🇴 Faroe Islands Flag" },
            { "Fr", "🇫🇷 France Flag" },
            { "FlagGa", "🇬🇦 Gabon Flag" },
            { "Gb", "🇬🇧 United Kingdom Flag" },
            { "FlagGd", "🇬🇩 Grenada Flag" },
            { "FlagGe", "🇬🇪 Georgia Flag" },
            { "FlagGf", "🇬🇫 French Guiana Flag" },
            { "FlagGg", "🇬🇬 Guernsey Flag" },
            { "FlagGh", "🇬🇭 Ghana Flag" },
            { "FlagGi", "🇬🇮 Gibraltar Flag" },
            { "FlagGl", "🇬🇱 Greenland Flag" },
            { "FlagGm", "🇬🇲 Gambia Flag" },
            { "FlagGn", "🇬🇳 Guinea Flag" },
            { "FlagGp", "🇬🇵 Guadeloupe Flag" },
            { "FlagGq", "🇬🇶 Equatorial Guinea Flag" },
            { "FlagGr", "🇬🇷 Greece Flag" },
            { "FlagGs", "🇬🇸 South Georgia & South Sandwich Islands Flag" },
            { "FlagGt", "🇬🇹 Guatemala Flag" },
            { "FlagGu", "🇬🇺 Guam Flag" },
            { "FlagGw", "🇬🇼 Guinea-Bissau Flag" },
            { "FlagGy", "🇬🇾 Guyana Flag" },
            { "FlagHk", "🇭🇰 Hong Kong SAR China Flag" },
            { "FlagHm", "🇭🇲 Heard & McDonald Islands Flag" },
            { "FlagHn", "🇭🇳 Honduras Flag" },
            { "FlagHr", "🇭🇷 Croatia Flag" },
            { "FlagHt", "🇭🇹 Haiti Flag" },
            { "FlagHu", "🇭🇺 Hungary Flag" },
            { "FlagIc", "🇮🇨 Canary Islands Flag" },
            { "FlagId", "🇮🇩 Indonesia Flag" },
            { "FlagIe", "🇮🇪 Ireland Flag" },
            { "FlagIl", "🇮🇱 Israel Flag" },
            { "FlagIm", "🇮🇲 Isle of Man Flag" },
            { "FlagIn", "🇮🇳 India Flag" },
            { "FlagIo", "🇮🇴 British Indian Ocean Territory Flag" },
            { "FlagIq", "🇮🇶 Iraq Flag" },
            { "FlagIr", "🇮🇷 Iran Flag" },
            { "FlagIs", "🇮🇸 Iceland Flag" },
            { "It", "🇮🇹 Italy Flag" },
            { "FlagJe", "🇯🇪 Jersey Flag" },
            { "FlagJm", "🇯🇲 Jamaica Flag" },
            { "FlagJo", "🇯🇴 Jordan Flag" },
            { "Jp", "🇯🇵 Japan Flag" },
            { "FlagKe", "🇰🇪 Kenya Flag" },
            { "FlagKg", "🇰🇬 Kyrgyzstan Flag" },
            { "FlagKh", "🇰🇭 Cambodia Flag" },
            { "FlagKi", "🇰🇮 Kiribati Flag" },
            { "FlagKm", "🇰🇲 Comoros Flag" },
            { "FlagKn", "🇰🇳 St. Kitts & Nevis Flag" },
            { "FlagKp", "🇰🇵 North Korea Flag" },
            { "Kr", "🇰🇷 South Korea Flag" },
            { "FlagKw", "🇰🇼 Kuwait Flag" },
            { "FlagKy", "🇰🇾 Cayman Islands Flag" },
            { "FlagKz", "🇰🇿 Kazakhstan Flag" },
            { "FlagLa", "🇱🇦 Laos Flag" },
            { "FlagLb", "🇱🇧 Lebanon Flag" },
            { "FlagLc", "🇱🇨 St. Lucia Flag" },
            { "FlagLi", "🇱🇮 Liechtenstein Flag" },
            { "FlagLk", "🇱🇰 Sri Lanka Flag" },
            { "FlagLr", "🇱🇷 Liberia Flag" },
            { "FlagLs", "🇱🇸 Lesotho Flag" },
            { "FlagLt", "🇱🇹 Lithuania Flag" },
            { "FlagLu", "🇱🇺 Luxembourg Flag" },
            { "FlagLv", "🇱🇻 Latvia Flag" },
            { "FlagLy", "🇱🇾 Libya Flag" },
            { "FlagMa", "🇲🇦 Morocco Flag" },
            { "FlagMc", "🇲🇨 Monaco Flag" },
            { "FlagMd", "🇲🇩 Moldova Flag" },
            { "FlagMe", "🇲🇪 Montenegro Flag" },
            { "FlagMf", "🇲🇫 St. Martin Flag" },
            { "FlagMg", "🇲🇬 Madagascar Flag" },
            { "FlagMh", "🇲🇭 Marshall Islands Flag" },
            { "FlagMk", "🇲🇰 Macedonia Flag" },
            { "FlagMl", "🇲🇱 Mali Flag" },
            { "FlagMm", "🇲🇲 Myanmar (Burma) Flag" },
            { "FlagMn", "🇲🇳 Mongolia Flag" },
            { "FlagMo", "🇲🇴 Macau SAR China Flag" },
            { "FlagMp", "🇲🇵 Northern Mariana Islands Flag" },
            { "FlagMq", "🇲🇶 Martinique Flag" },
            { "FlagMr", "🇲🇷 Mauritania Flag" },
            { "FlagMs", "🇲🇸 Montserrat Flag" },
            { "FlagMt", "🇲🇹 Malta Flag" },
            { "FlagMu", "🇲🇺 Mauritius Flag" },
            { "FlagMv", "🇲🇻 Maldives Flag" },
            { "FlagMw", "🇲🇼 Malawi Flag" },
            { "FlagMx", "🇲🇽 Mexico Flag" },
            { "FlagMy", "🇲🇾 Malaysia Flag" },
            { "FlagMz", "🇲🇿 Mozambique Flag" },
            { "FlagNa", "🇳🇦 Namibia Flag" },
            { "FlagNc", "🇳🇨 New Caledonia Flag" },
            { "FlagNe", "🇳🇪 Niger Flag" },
            { "FlagNf", "🇳🇫 Norfolk Island Flag" },
            { "FlagNg", "🇳🇬 Nigeria Flag" },
            { "FlagNi", "🇳🇮 Nicaragua Flag" },
            { "FlagNl", "🇳🇱 Netherlands Flag" },
            { "FlagNo", "🇳🇴 Norway Flag" },
            { "FlagNp", "🇳🇵 Nepal Flag" },
            { "FlagNr", "🇳🇷 Nauru Flag" },
            { "FlagNu", "🇳🇺 Niue Flag" },
            { "FlagNz", "🇳🇿 New Zealand Flag" },
            { "FlagOm", "🇴🇲 Oman Flag" },
            { "FlagPa", "🇵🇦 Panama Flag" },
            { "FlagPe", "🇵🇪 Peru Flag" },
            { "FlagPf", "🇵🇫 French Polynesia Flag" },
            { "FlagPg", "🇵🇬 Papua New Guinea Flag" },
            { "FlagPh", "🇵🇭 Philippines Flag" },
            { "FlagPk", "🇵🇰 Pakistan Flag" },
            { "FlagPl", "🇵🇱 Poland Flag" },
            { "FlagPm", "🇵🇲 St. Pierre & Miquelon Flag" },
            { "FlagPn", "🇵🇳 Pitcairn Islands Flag" },
            { "FlagPr", "🇵🇷 Puerto Rico Flag" },
            { "FlagPs", "🇵🇸 Palestinian Territories Flag" },
            { "FlagPt", "🇵🇹 Portugal Flag" },
            { "FlagPw", "🇵🇼 Palau Flag" },
            { "FlagPy", "🇵🇾 Paraguay Flag" },
            { "FlagQa", "🇶🇦 Qatar Flag" },
            { "FlagRe", "🇷🇪 Réunion Flag" },
            { "FlagRo", "🇷🇴 Romania Flag" },
            { "FlagRs", "🇷🇸 Serbia Flag" },
            { "Ru", "🇷🇺 Russia Flag" },
            { "FlagRw", "🇷🇼 Rwanda Flag" },
            { "FlagSa", "🇸🇦 Saudi Arabia Flag" },
            { "FlagSb", "🇸🇧 Solomon Islands Flag" },
            { "FlagSc", "🇸🇨 Seychelles Flag" },
            { "FlagSd", "🇸🇩 Sudan Flag" },
            { "FlagSe", "🇸🇪 Sweden Flag" },
            { "FlagSg", "🇸🇬 Singapore Flag" },
            { "FlagSh", "🇸🇭 St. Helena Flag" },
            { "FlagSi", "🇸🇮 Slovenia Flag" },
            { "FlagSj", "🇸🇯 Svalbard & Jan Mayen Flag" },
            { "FlagSk", "🇸🇰 Slovakia Flag" },
            { "FlagSl", "🇸🇱 Sierra Leone Flag" },
            { "FlagSm", "🇸🇲 San Marino Flag" },
            { "FlagSn", "🇸🇳 Senegal Flag" },
            { "FlagSo", "🇸🇴 Somalia Flag" },
            { "FlagSr", "🇸🇷 Suriname Flag" },
            { "FlagSs", "🇸🇸 South Sudan Flag" },
            { "FlagSt", "🇸🇹 São Tomé & Príncipe Flag" },
            { "FlagSv", "🇸🇻 El Salvador Flag" },
            { "FlagSx", "🇸🇽 Sint Maarten Flag" },
            { "FlagSy", "🇸🇾 Syria Flag" },
            { "FlagSz", "🇸🇿 Swaziland Flag" },
            { "FlagTa", "🇹🇦 Tristan da Cunha Flag" },
            { "FlagTc", "🇹🇨 Turks & Caicos Islands Flag" },
            { "FlagTd", "🇹🇩 Chad Flag" },
            { "FlagTf", "🇹🇫 French Southern Territories Flag" },
            { "FlagTg", "🇹🇬 Togo Flag" },
            { "FlagTh", "🇹🇭 Thailand Flag" },
            { "FlagTj", "🇹🇯 Tajikistan Flag" },
            { "FlagTk", "🇹🇰 Tokelau Flag" },
            { "FlagTl", "🇹🇱 Timor-Leste Flag" },
            { "FlagTm", "🇹🇲 Turkmenistan Flag" },
            { "FlagTn", "🇹🇳 Tunisia Flag" },
            { "FlagTo", "🇹🇴 Tonga Flag" },
            { "FlagTr", "🇹🇷 Turkey Flag" },
            { "FlagTt", "🇹🇹 Trinidad & Tobago Flag" },
            { "FlagTv", "🇹🇻 Tuvalu Flag" },
            { "FlagTw", "🇹🇼 Taiwan Flag" },
            { "FlagTz", "🇹🇿 Tanzania Flag" },
            { "FlagUa", "🇺🇦 Ukraine Flag" },
            { "FlagUg", "🇺🇬 Uganda Flag" },
            { "FlagUn", "🇺🇳 United Nations Flag" },
            { "Us", "🇺🇸 United States Flag" },
            { "FlagUy", "🇺🇾 Uruguay Flag" },
            { "FlagUz", "🇺🇿 Uzbekistan Flag" },
            { "FlagVa", "🇻🇦 Vatican City Flag" },
            { "FlagVc", "🇻🇨 St. Vincent & Grenadines Flag" },
            { "FlagVe", "🇻🇪 Venezuela Flag" },
            { "FlagVg", "🇻🇬 British Virgin Islands Flag" },
            { "FlagVi", "🇻🇮 U.S. Virgin Islands Flag" },
            { "FlagVn", "🇻🇳 Vietnam Flag" },
            { "FlagVu", "🇻🇺 Vanuatu Flag" },
            { "FlagWf", "🇼🇫 Wallis & Futuna Flag" },
            { "FlagWs", "🇼🇸 Samoa Flag" },
            { "FlagXk", "🇽🇰 Kosovo Flag" },
            { "FlagYe", "🇾🇪 Yemen Flag" },
            { "FlagYt", "🇾🇹 Mayotte Flag" },
            { "FlagZa", "🇿🇦 South Africa Flag" },
            { "FlagZm", "🇿🇲 Zambia Flag" },
            { "FlagZw", "🇿🇼 Zimbabwe Flag" },
            { "FlagEngland", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England Flag" },
            { "FlagScotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland Flag" },
            { "FlagWales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales Flag" }
            };
            return data;
        }
    }
    
}
